INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("kit_horse_brush"               ,"Horsebrush"           , 10, 1, 'item_standard', 1, '{}', 'Horsebrush') 		ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("consumable_carrot" 	        ,"Carrot"               , 10, 1, 'item_standard', 1, '{}', 'Carrot') 	 		ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("consumable_sugarcube" 			,"Sugar Cube"           , 10, 1, 'item_standard', 1, '{}', 'Sugar Cube') 		ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("consumable_haycube" 	        ,"Hay cube"             , 10, 1, 'item_standard', 1, '{}', 'Hay cube') 	 		ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("consumable_apple" 	       		,"Apple"                , 10, 1, 'item_standard', 1, '{}', 'Apple') 			ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("kit_horse_reviver"    		    ,"Horse Reviver"        , 10, 1, 'item_standard', 1, '{}', 'Horse Reviver') 	ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("consumable_horse_ointment"     ,"Horse Ointment"       , 10, 1, 'item_standard', 1, '{}', 'Horse Ointment') 	ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("kit_hoof_knife"     			,"Hoof Knife"       	, 10, 1, 'item_standard', 1, '{}', 'Hoof Knife') 		ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)  VALUES ("kit_lunging_rope"     			,"Lunging Rope"       	, 10, 1, 'item_standard', 1, '{}', 'Lunging rope') 		ON DUPLICATE KEY UPDATE  `item` = VALUES(`item`), `label`= VALUES(`label`),`limit`= VALUES(`limit`), `can_remove`= VALUES(`can_remove`), `type`= VALUES(`type`), `usable`= VALUES(`usable`), `metadata`= VALUES(`metadata`), `desc`= VALUES(`desc`);  
