ALTER TABLE `sirevlc_horses_v3`
  MODIFY COLUMN `AGE` FLOAT(5,1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `AGE_UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP AFTER `STASHSLOTS`,
  ADD COLUMN IF NOT EXISTS `SHOES_UPDATED_AT` DATETIME DEFAULT NULL AFTER `AGE_UPDATED_AT`,
  ADD COLUMN IF NOT EXISTS `BREED_COUNT` INT(5) NOT NULL DEFAULT 0 AFTER `SHOES_UPDATED_AT`,
  ADD COLUMN IF NOT EXISTS `CAN_BREED` INT(1) NOT NULL DEFAULT 1 AFTER `BREED_COUNT`,
  ADD COLUMN IF NOT EXISTS `OUTTER_HEALTH` INT(3) NOT NULL DEFAULT 100 AFTER `HEALTH`,
  ADD COLUMN IF NOT EXISTS `OUTTER_STAMINA` INT(3) NOT NULL DEFAULT 100 AFTER `STAMINA`,
  ADD COLUMN IF NOT EXISTS `BREEDING_TIMESTAMP` DATETIME NULL;
 