Config.Scenarios = {
	["sit"] = {
		name = "Sit on Ground 1",
		scenario = "WORLD_HUMAN_SIT_GROUND",
	},
	["kneelchest"] = {
		name = "Kneel/Lay (Chest)",
		scenario = "PROP_PLAYER_PRPTY_KNEEL_CHEST",
	},
	["sleepbedroll"] = {
		name = "Sleep (Bedroll)",
		scenario = "WORLD_PLAYER_SLEEP_BEDROLL",
	},
	["squat"] = {
		name = "Squat",
		scenario = "WORLD_PLAYER_CAMP_FIRE_SQUAT",
	},
	["fertilize"] = {
		name = "Fertilize",
		scenario = "WORLD_PLAYER_CHORES_FEED_CHICKENS",
	},
	["leanon"] = {
		name = "Lean On",
		scenario = "PROP_PLAYER_PRPTY_SHAVE",
		sex = "male",
	},
	["leanon2"] = {
		name = "Lean On 2",
		scenario = "WORLD_PLAYER_MOONSHINE_SERVING",
	},
	["leanon3"] = {
		name = "Lean On 3",
		scenario = "WORLD_PLAYER_MOONSHINE_CUSTOMER",
	},
	["leanon4"] = {
		name = "Lean On 4",
		scenario = "WORLD_HUMAN_SHOPKEEPER_MP",
	},
	["leanon5"] = {
		name = "Lean On 5",
		scenario = "WORLD_PLAYER_SHOPPING",
	},
	["leanrailing"] = {
		name = "Lean on Railing",
		scenario = "WORLD_HUMAN_LEAN_RAILING_NO_PROPS"
	},
	["leanrailing2"] = {
		name = "Lean on Railing (Smoking)",
		scenario = "WORLD_HUMAN_LEAN_RAILING_SMOKING",
	},
	["leanrailing3"] = {
		name = "Lean on Railing (Drinking)",
		scenario = "WORLD_HUMAN_LEAN_RAILING_DRINKING",
	},
	["leanrailing4"] = {
		name = "Lean on Railing (Interaction)",
		scenario = "WORLD_HUMAN_LEAN_RAILING_INTERACTION",
	},
	["leanrailing5"] = {
		name = "Lean on Railing (Dynamic)",
		scenario = "WORLD_HUMAN_LEAN_RAILING_DYNAMIC",
	},
	["leanrailingleft"] = {
		name = "Lean on Railing (Left)",
		scenario = "WORLD_HUMAN_LEAN_RAILING_LEFT",
	},
	["leanleft"] = {
		name = "Lean Post Left",
		scenario = "WORLD_HUMAN_LEAN_POST_LEFT",
	},
	["leanleft2"] = {
		name = "Lean Post Left 2",
		scenario = "WORLD_HUMAN_LEAN_POST_LEFT_MOONSHINE",
	},
	["leanleft3"] = {
		name = "Lean Post Left 3 (Hand Planted)",
		scenario = "WORLD_HUMAN_LEAN_POST_LEFT_HAND_PLANTED",
	},
	["leanleft4"] = {
		name = "Lean Wall Left",
		scenario = "WORLD_HUMAN_LEAN_WALL_LEFT",
	},

	["leanright"] = {
		name = "Lean Post Right",
		scenario = "WORLD_HUMAN_LEAN_POST_RIGHT",
	},
	["leanright2"] = {
		name = "Lean Post Right (Hand Planted)",
		scenario = "WORLD_HUMAN_LEAN_POST_RIGHT_HAND_PLANTED",
	},
	["leanright3"] = {
		name = "Lean Post Right 2",
		scenario = "WORLD_HUMAN_LEAN_WALL_RIGHT",
	},
	["leanback"] = {
		name = "Lean Back",
		scenario = "WORLD_HUMAN_LEAN_BACK_WALL",
	},
	["leanback2"] = {
		name = "Lean Back 2",
		scenario = "WORLD_HUMAN_LEAN_BACK_WALL_NO_PROPS",
	},
	["leanback3"] = {
		name = "Lean Back 3 (Drinking)",
		scenario = "WORLD_HUMAN_LEAN_BACK_WALL_DRINKING",
	},
	["leanback4"] = {
		name = "Lean Back 4 (Whittle)",
		scenario = "WORLD_HUMAN_LEAN_BACK_WHITTLE",
	},
	["leanback5"] = {
		name = "Lean Back 5 (Rail Drinking)",
		scenario = "WORLD_HUMAN_LEAN_BACK_RAILING_DRINKING",
	},
	["leanback6"] = {
		name = "Lean Back 6 (Railing)",
		scenario = "WORLD_HUMAN_LEAN_BACK_RAILING",
	},

	["leanreading"] = {
		name = "Lean Reading",
		scenario = "WORLD_CAMP_LENNY_LEAN_READING",
	},
	["leanwallpistol"] = {
		name = "Lean Wall (Pistol Check)",
		scenario = "WORLD_HUMAN_LEAN_CHECK_PISTOL",
	},
	["leanwallknife"] = {
		name = "Lean Wall (Sharpen Knife)",
		scenario = "WORLD_HUMAN_LEAN_TABLE_SHARPEN_KNIFE",
	},

	["leanbarrel"] = {
		name = "Lean Back Barrel",
		scenario = "WORLD_HUMAN_LEAN_BARREL",
	},
	["leanfencehigh"] = {
		name = "Lean Fence High",
		scenario = "WORLD_HUMAN_LEAN_FENCE_FWD_CHECK_OUT_LIVESTOCK",
	},
	["carvewall"] = {
		name = "Carve Wall",
		scenario = "RANSACK_BRICK_WALL",
	},
	["reachchimney"] = {
		name = "Reach Up Chimney",
		scenario = "RANSACK_REACH_IN_CHIMNEY_LOOTING",
	},
	["carrycup"] = {
		name = "Carry Cup",
		scenario = "WORLD_PLAYER_MOONSHINE_SELF_SERVE_CASK",
	},
	["carrycupdrunk"] = {
		name = "Carry Cup (Drunk)",
		scenario = "WORLD_PLAYER_MOONSHINE_SELF_SERVE_BAR",
	},
	["washface"] = {
		name = "Wash Face (Barrel)",
		scenario = "PROP_PLAYER_WASH_FACE_BARREL",
	},
	["carrybeer"] = {
		name = "Carry Beer",
		scenario = "WORLD_HUMAN_BOTTLE_PICKUP_BOX_TABLE_BEER_CULTURE",
	},
	["carrywhiskey"] = {
		name = "Carry Whiskey",
		scenario = "WORLD_HUMAN_BOTTLE_PICKUP_BOX_TABLE_JD_CULTURE",
	},
	["drinkcoffee"] = {
		name = "Drink Coffee",
		scenario = "WORLD_HUMAN_COFFEE_DRINK"
	},
	["smokepipe"] = {
		name = "Smoke Pipe",
		scenario = "WORLD_HUMAN_SMOKE_CARRYING",
	},
	["handonhip"] = {
		name = "Hand on Hip",
		scenario = "WORLD_HUMAN_STAND_WAITING_CARRYING",
	},
	["standwaiting"] = {
		name = "Stand Waiting",
		scenario = "MP_COOP_LOBBY_STANDING_A",
	},
	["standwaiting2"] = {
		name = "Stand Waiting 2",
		scenario = "MP_COOP_LOBBY_STANDING_B",
	},
	["standwaiting3"] = {
		name = "Stand Waiting 3",
		scenario = "MP_COOP_LOBBY_STANDING_C",
	},
	["standwaiting4"] = {
		name = "Stand Waiting 4",
		scenario = "MP_COOP_LOBBY_STANDING_D",
	},
	["standwaiting5"] = {
		name = "Stand Waiting 5",
		scenario = "MP_LOBBY_STANDING_A",
	},
	["standwaiting6"] = {
		name = "Stand Waiting 6",
		scenario = "MP_LOBBY_STANDING_B",
	},
	["standwaiting7"] = {
		name = "Stand Waiting 7",
		scenario = "MP_LOBBY_STANDING_C",
	},
	["standwaiting8"] = {
		name = "Stand Waiting 8",
		scenario = "MP_LOBBY_STANDING_D",
	},
	["standwaiting9"] = {
		name = "Stand Waiting 9",
		scenario = "MP_LOBBY_STANDING_E",
	},
	["standwaiting10"] = {
		name = "Stand Waiting 10",
		scenario = "MP_LOBBY_STANDING_F",
	},
	["standwaiting11"] = {
		name = "Stand Waiting 11",
		scenario = "MP_LOBBY_STANDING_G",
	},
	["standwaiting12"] = {
		name = "Stand Waiting 12",
		scenario = "MP_LOBBY_STANDING_H",
	},
	["intensestance"] = {
		name = "Intense Stance",
		scenario = "MP_LOBBY_PHNS_STANDING_A",
	},
	["crouch"] = {
		name = "Crouch",
		scenario = "MP_LOBBY_CROUCHING_A",
	},
	["crouch2"] = {
		name = "Crouch 2",
		scenario = "MP_LOBBY_CROUCHING_B",
	},
	["putinpocket"] = {
		name = "Put In Pocket",
		scenario = "PROP_PLAYER_PICKUP_PIRATE_SKELETON_CLOTHING",
	},
	["peekwindow"] = {
		name = "Peek Window",
		scenario = "WORLD_PLAYER_PEEK_WINDOW",
	},
	["smokecigar"] = {
		name = "Smoke Cigar",
		scenario = "WORLD_CAMP_DUTCH_SMOKE_CIGAR",
	},
	["smokecigargus"] = {
		name = "Smoke Cigar (Gus)",
		scenario = "WORLD_CAMP_DUTCH_SMOKE_CIGAR_GUS",
	},
	["laybackfire"] = {
		name = "Lay Back at Campfire",
		scenario = "WORLD_CAMP_FIRE_LAY_BACK_GROUND",
	},
	["sitsmoke"] = {
		name = "Sit and Smoke",
		scenario = "WORLD_HUMAN_SIT_SMOKE",
	},
	["writenotebook"] = {
		name = "Write Notebook",
		scenario = "WORLD_HUMAN_WRITE_NOTEBOOK",
	},
	["pee"] = {
		name = "Pee",
		scenario = "WORLD_HUMAN_PEE",
	},
	["mourn"] = {
		name = "Mourn",
		scenario = "WORLD_HUMAN_GRAVE_MOURNING",
	},
	["kneel"] = {
		name = "Kneel",
		scenario = "SC_WORLD_HUMAN_KNEELING",
	},
	["cleantable"] = {
		name = "Clean Table",
		scenario = "WORLD_HUMAN_CLEAN_TABLE",
	},
	["bartendercleanglass"] = {
		name = "Bartender Clean Glass",
		scenario = "WORLD_HUMAN_BARTENDER_CLEAN_GLASS",
	},
	["playguitar1"] = {
		name = "Play Guitar",
		scenario = "WORLD_HUMAN_SIT_GUITAR",
	},
	["playguitar2"] = {
		name = "Play Guitar 2",
		scenario = "WORLD_HUMAN_SIT_GUITAR_UPBEAT",
	},
	["playguitar3"] = {
		name = "Play Guitar 3",
		scenario = "WORLD_HUMAN_SIT_GUITAR_DOWNBEAT",
	},
	["playguitar4"] = {
		name = "Play Guitar 4",
		scenario = "WORLD_HUMAN_SIT_GUITAR_BLUES",
	},
	["playtrumpet"] = {
		name = "WORLD_HUMAN_TRUMPET",
		scenario = "WORLD_HUMAN_TRUMPET",
	},
	["fancysmoke"] = {
		name = "Fancy Smoke",
		scenario = "WORLD_HUMAN_SMOKE_NAZAR"
	},
	["fillbucket"] = {
		name = "Fill Bucket",
		scenario = "WORLD_HUMAN_BUCKET_FILL",
	},
	["vomitwall"] = {
		name = "Vomit on Wall",
		scenario = "SC_AMB_VIG_VOMIT_WALL",
	},
	["banktellerlean"] = {
		name = "Bank Teller",
		scenario = "WORLD_HUMAN_VAL_BANKTELLER",
	},
	["bible"] = {
		name = "Preach Hold Up Bible",
		scenario = "SCRIPT_RETB_PREACHER",
	},
	["preach"] = {
		name = "Preach The Bible",
		scenario = "SC_WORLD_HUMAN_PREACHER",
	},
	["usesledgehammer"] = {
		name = "Use Sledgehammer",
		scenario = "WORLD_HUMAN_2H_TOOL",
	},
	["planevil"] = {
		name = "Rub Hands Together (Evil)",
		scenario = "SCRIP_REMC_RET_MALE_A_POSE2",
	},
	["planevil2"] = {
		name = "Rub Hands Together 2 (Evil)",
		scenario = "SCRIP_REMC_RET_MALE_A_POSE3",
	},
	["drunksleep"] = {
		name = "Sleep (Drunk)",
		scenario = "WORLD_HUMAN_RE_LOST_DRUNK_SLEEP",
	},
	["pokefire"] = {
		name = "Poke Fire With Stick",
		scenario = "SC_CAMP_VIG_FIRE_POKE",
	},
	["blowfire"] = {
		name = "Blow on Fire",
		scenario = "SC_CAMP_VIG_FIRE_BLOW",
	},
	["leanon"] = {
		name = "Lean On (Planning)",
		scenario = "SCRIPT_CF_ODRIS_PLANROB_01_MALE_A",
	},
	["foldarmsplan"] = {
		name = "Fold Arms (Planning)",
		scenario = "SCRIPT_CF_ODRIS_PLANROB_01_MALE_B",
	},
	["smokeidle"] = {
		name = "Smoke Idle",
		scenario = "WORLD_HUMAN_SMOKE",
	},
	["smokeidle2"] = {
		name = "Smoke Idle 2",
		scenario = "WORLD_HUMAN_SMOKE_INTERACTION",
	},
	["smokenervous"] = {
		name = "Smoke Nervous",
		scenario = "WORLD_HUMAN_SMOKE_NERVOUS_STRESSED",
	},
	["fleshingskin"] = {
		name = "Flesh Skin",
		scenario = "PROP_HUMAN_TANNING_RACK_FLESHING",
	},
	["washwater"] = {
		name = "Wash Water",
		scenario = "PROP_HUMAN_TANNING_RACK_BRAINS",
	},
}

-- Sit-behind entries follow the same style as other config tables in this file.
-- Supported fields:
-- name     = Label shown in menu/favorites
-- scenario = Scenario hash name
-- offset   = Positional XYZ offset applied when starting sit-behind scenario
-- sex      = Optional "male" or "female" restriction
Config.SitBehindScenarios = {
	[1] = { name = "Bench", scenario = "GENERIC_SEAT_BENCH_SCENARIO", offset = vector3(0.0, 0.0, 0.0) },
	[2] = { name = "Chair", scenario = "GENERIC_SEAT_CHAIR_SCENARIO", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[3] = { name = "Table Chair", scenario = "GENERIC_SEAT_CHAIR_TABLE_SCENARIO", offset = vector3(0.0, 0.0, 0.0) },
	[4] = { name = "Porch Drink", scenario = "MP_LOBBY_PROP_HUMAN_SEAT_BENCH_PORCH_DRINKING", offset = vector3(0.0, 0.0, 0.0) },
	[5] = { name = "Porch Smoke", scenario = "MP_LOBBY_PROP_HUMAN_SEAT_BENCH_PORCH_SMOKING", offset = vector3(0.0, 0.0, 0.0) },
	[6] = { name = "Lobby Chair", scenario = "MP_LOBBY_PROP_HUMAN_SEAT_CHAIR", offset = vector3(0.0, 0.0, 0.0) },
	[7] = { name = "Knife Chair", scenario = "MP_LOBBY_PROP_HUMAN_SEAT_CHAIR_KNIFE_BADASS", offset = vector3(0.0, 0.0, 0.0) },
	[8] = { name = "Whittle Chair", scenario = "MP_LOBBY_PROP_HUMAN_SEAT_CHAIR_WHITTLE", offset = vector3(0.0, 0.0, 0.0) },
	[9] = { name = "Campfire Chair", scenario = "PROP_CAMP_FIRE_SEAT_CHAIR", offset = vector3(0.0, 0.0, 0.0) },
	[10] = { name = "Campfire Box", scenario = "PROP_HUMAN_CAMP_FIRE_SEAT_BOX", offset = vector3(0.0, 0.0, 0.0) },
	[11] = { name = "Concertina", scenario = "PROP_HUMAN_SEAT_BENCH_CONCERTINA", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[12] = { name = "Concertina Down Beat", scenario = "PROP_HUMAN_SEAT_BENCH_CONCERTINA_DOWNBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[13] = { name = "Concertina Up Beat", scenario = "PROP_HUMAN_SEAT_BENCH_CONCERTINA_UPBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[14] = { name = "Fiddle", scenario = "PROP_HUMAN_SEAT_BENCH_FIDDLE", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[15] = { name = "Fiddle Down Beat", scenario = "PROP_HUMAN_SEAT_BENCH_FIDDLE_DOWNBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[16] = { name = "Fiddle Up Beat", scenario = "PROP_HUMAN_SEAT_BENCH_FIDDLE_UPBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[17] = { name = "Jaw Harp", scenario = "PROP_HUMAN_SEAT_BENCH_JAW_HARP", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[18] = { name = "Jaw Harp Up Beat", scenario = "PROP_HUMAN_SEAT_BENCH_JAW_HARP_UPBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[19] = { name = "Jaw Harp Down Beat", scenario = "PROP_HUMAN_SEAT_BENCH_JAW_HARP_DOWNBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[20] = { name = "Mandolin", scenario = "PROP_HUMAN_SEAT_BENCH_MANDOLIN", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[21] = { name = "Mandolin Down Beat", scenario = "PROP_HUMAN_SEAT_BENCH_MANDOLIN_DOWNBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[22] = { name = "Mandolin Up Beat", scenario = "PROP_HUMAN_SEAT_BENCH_MANDOLIN_UPBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[23] = { name = "Banjo", scenario = "PROP_HUMAN_SEAT_CHAIR_BANJO", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[24] = { name = "Banjo Down Beat", scenario = "PROP_HUMAN_SEAT_CHAIR_BANJO_DOWNBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[25] = { name = "Banjo Up Beat", scenario = "PROP_HUMAN_SEAT_CHAIR_BANJO_UPBEAT", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[26] = { name = "Clean Saddle", scenario = "PROP_HUMAN_SEAT_CHAIR_CLEAN_SADDLE", offset = vector3(0.0, 0.0, 0.0) },
	[27] = { name = "Crab Trap", scenario = "PROP_HUMAN_SEAT_CHAIR_CRAB_TRAP", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[28] = { name = "Cigar Chair", scenario = "PROP_HUMAN_SEAT_CHAIR_CIGAR", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[29] = { name = "Grooming", scenario = "PROP_HUMAN_SEAT_CHAIR_GROOMING_GROSS", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[30] = { name = "Grooming Posh", scenario = "PROP_HUMAN_SEAT_CHAIR_GROOMING_POSH", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[31] = { name = "Guitar Chair", scenario = "PROP_HUMAN_SEAT_CHAIR_GUITAR", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[32] = { name = "Knitting", scenario = "PROP_HUMAN_SEAT_CHAIR_KNITTING", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[33] = { name = "Porch Rest", scenario = "PROP_HUMAN_SEAT_CHAIR_PORCH", offset = vector3(0.0, 0.0, 0.0) },
	[34] = { name = "Reading", scenario = "PROP_HUMAN_SEAT_CHAIR_READING", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[35] = { name = "Tired Bench", scenario = "PROP_HUMAN_SEAT_BENCH_TIRED_SHAKY", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[36] = { name = "Langton Chair", scenario = "PROP_HUMAN_SEAT_CHAIR_LANGTON", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[37] = { name = "Roll Smoke", scenario = "PROP_HUMAN_SEAT_CHAIR_SMOKE_ROLL", offset = vector3(0.0, 0.0, 0.0) },
	[38] = { name = "Mortar Pestle", scenario = "PROP_HUMAN_SEAT_CHAIR_MORTAR_PESTLE", offset = vector3(0.0, 0.0, 0.0) },
	[39] = { name = "Carve Lure", scenario = "PROP_HUMAN_SEAT_CHAIR_CARVE_LURE", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[40] = { name = "Plan Rob", scenario = "SCRIPT_CF_ODRIS_PLANROB_02_MALE_C", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[41] = { name = "Badass Knife", scenario = "GFH_PROP_HUMAN_SEAT_CHAIR_KNIFE_BADASS", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[42] = { name = "Read Book", scenario = "PROP_HUMAN_SEAT_CHAIR_READ_BOOK_TRELAWNY", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[43] = { name = "Barber Seat", scenario = "PROP_PLAYER_BARBER_SEAT", offset = vector3(0.0, 0.0, 0.0) },
	[44] = { name = "Clean Boots", scenario = "PROP_HUMAN_SEAT_CRATE_CLEAN_BOOTS", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[45] = { name = "Moonshine Drink", scenario = "PROP_HUMAN_SEAT_CHAIR_DRINKING_MOONSHINE", offset = vector3(0.0, 0.0, 0.0) },
	[46] = { name = "Porch Moonshine", scenario = "PROP_HUMAN_SEAT_BENCH_PORCH_DRINKING_MOONSHINE", offset = vector3(0.0, 0.0, 0.0) },
	[47] = { name = "Table Moonshine", scenario = "PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_MOONSHINE", offset = vector3(0.0, 0.0, 0.0) },
	[48] = { name = "Table Drink", scenario = "PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING", offset = vector3(0.0, 0.0, 0.0) },
	[49] = { name = "Sketching", scenario = "PROP_HUMAN_SEAT_CHAIR_SKETCHING", offset = vector3(0.0, 0.0, 0.0) },
	[50] = { name = "Sketching Harriet", scenario = "PROP_HUMAN_SEAT_CHAIR_SKETCHING_HARRIET", offset = vector3(0.0, 0.0, 0.0) },
	[51] = { name = "Sad Sit", scenario = "PROP_HUMAN_SEAT_CHAIR_SAD", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[52] = { name = "Sharpen Knife", scenario = "PROP_HUMAN_SEAT_CHAIR_SHARPEN_KNIFE_GUS", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[53] = { name = "Passed Out", scenario = "PROP_HUMAN_PASSED_OUT_TABLE", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[54] = { name = "Fishing Rod", scenario = "PROP_HUMAN_SEAT_CHAIR_FISHING_ROD", offset = vector3(0.0, 0.0, 0.0) },
	[55] = { name = "Campfire Seated", scenario = "PROP_CAMP_FIRE_SEATED", offset = vector3(0.0, 0.0, 0.0) },
	[56] = { name = "Jack Read", scenario = "PROP_CAMP_JACK_ES_READ_SEAT", offset = vector3(0.0, 0.0, 0.0) },
	[57] = { name = "Jack Fire Box", scenario = "WORLD_CAMP_JACK_ES_FIRE_SEAT_BOX", offset = vector3(0.0, 0.0, 0.0) },
	[58] = { name = "Campfire Drink", scenario = "CC_PROP_CAMP_FIRE_SEATED_DRINKING", offset = vector3(0.0, 0.0, 0.0) },
	[59] = { name = "Campfire Bench", scenario = "PROP_CAMP_FIRE_SEAT_BENCH", offset = vector3(0.0, 0.0, 0.0) },
	[60] = { name = "Craft Knives", scenario = "PROP_CAMP_SEAT_CHAIR_CRAFT_POISON_KNIVES", offset = vector3(0.0, 0.0, 0.0) },
	[61] = { name = "Log Lean", scenario = "PROP_CAMP_FIRE_SEAT_LOG_LEAN", offset = vector3(0.0, 0.0, 0.0) },
	[62] = { name = "Sore Joints", scenario = "SC_CAMP_VIG_SORE_JOINTS_MALE", offset = vector3(0.0, 0.0, 0.0) },
	[63] = { name = "Lobby Seat A", scenario = "MP_LOBBY_SEATED_A", offset = vector3(0.0, 0.0, 0.0) },
	[64] = { name = "Lobby Seat B", scenario = "MP_LOBBY_SEATED_B", offset = vector3(0.0, 0.0, 0.0) },
	[65] = { name = "Lobby Seat C", scenario = "MP_LOBBY_SEATED_C", offset = vector3(0.0, 0.0, 0.0) },
	[66] = { name = "Lobby Seat D", scenario = "MP_LOBBY_SEATED_D", offset = vector3(0.0, 0.0, 0.0) },
	[67] = { name = "Lobby Seat E", scenario = "MP_LOBBY_SEATED_E", offset = vector3(0.0, 0.0, 0.0) },
	[68] = { name = "Lobby Seat F", scenario = "MP_LOBBY_SEATED_F", offset = vector3(0.0, 0.0, 0.0) },
	[69] = { name = "Clean Rifle", scenario = "PROP_HUMAN_SEAT_CHAIR_TABLE_CLEAN_RIFLE_SMOKE_JOE", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[70] = { name = "Desk Writing", scenario = "GFH_PROP_HUMAN_SIT_DESK_WRITING", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
	[71] = { name = "Drunk Camp", scenario = "PROP_PLAYER_RE_DRUNK_CAMP_SIT", offset = vector3(0.0, 0.0, 0.0) },
	[72] = { name = "Bench Back", scenario = "PROP_HUMAN_SEAT_BENCH_BACK", offset = vector3(0.0, 0.0, 0.0) },
	[73] = { name = "Bench Front", scenario = "PROP_HUMAN_SEAT_BENCH", offset = vector3(0.0, 0.0, 0.0) },
	[74] = { name = "Fan Table", scenario = "PROP_HUMAN_SEAT_CHAIR_TABLE_FAN_WHORE", offset = vector3(0.0, 0.0, 0.0), sex = "female" },
	[75] = { name = "Train Smoke", scenario = "PROP_HUMAN_SEAT_CHAIR_SMOKING_TRAIN", offset = vector3(0.0, 0.0, 0.0) },
	[76] = { name = "Train Drink", scenario = "PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_TRAIN", offset = vector3(0.0, 0.0, 0.0) },
	[77] = { name = "Train Chair", scenario = "PROP_HUMAN_SEAT_CHAIR_TRAIN", offset = vector3(0.0, 0.0, 0.0) },
	[78] = { name = "Train Bench", scenario = "PROP_HUMAN_SEAT_BENCH_TRAIN", offset = vector3(0.0, 0.0, 0.0) },
	-- [79] = { name = "Chair Drink", scenario = "PROP_HUMAN_SEAT_CHAIR_DRINKING", offset = vector3(0.0, 0.0, -2.0) },
	-- [80] = { name = "Play Knife", scenario = "PROP_HUMAN_SEAT_CHAIR_PLAY_KNIFE", offset = vector3(0.0, 0.0, 0.0), sex = "male" },
}

local function BuildSitInteractionLabel(index, scenarioEntry)
	if scenarioEntry and scenarioEntry.name and scenarioEntry.name ~= "" then
		return scenarioEntry.name .. " (Behind)"
	end
	if not scenarioEntry or not scenarioEntry.scenario or scenarioEntry.scenario == "" then
		return "Sit Behind"
	end
	return "Sit Behind - " .. tostring(index)
end

Config.SitInteractionEntries = {
	["sit_ledge_front"] = {
		name = "Sit Ledge - ~COLOR_GREEN~Front~q~",
		command = "ledge",
		scenario = "WORLD_HUMAN_SEAT_LEDGE",
		offset = 0.0,
	}
}

for index, scenarioEntry in ipairs(Config.SitBehindScenarios) do
	local scenarioName = scenarioEntry and scenarioEntry.scenario
	local scenarioOffset = scenarioEntry and scenarioEntry.offset or vector3(0.0, 0.0, 0.0)
	Config.SitInteractionEntries["sit_behind_" .. tostring(index)] = {
		name = BuildSitInteractionLabel(index, scenarioEntry),
		command = "behind",
		scenario = scenarioName,
		offset = scenarioOffset,
		sex = scenarioEntry and scenarioEntry.sex or nil,
		behindIndex = index,
	}
end

Config.NativeEmotes = {
	["praise_1"]                = { name = "Praise", emote = "KIT_EMOTE_REACTION_AMAZED_1" },
	["flex"]                    = { name = "Flex", emote = "KIT_EMOTE_ACTION_FLEX_1" },
	["greeting_2"]              = { name = "Wave Near", emote = "KIT_EMOTE_GREET_WAVENEAR_1" },
	["wave"]                    = { name = "Wave", emote = "KIT_EMOTE_GREET_GENTLEWAVE_1" },
	["hattip"]                  = { name = "Hat Tip", emote = "KIT_EMOTE_GREET_TIP_HAT_1" },
	["pleasure_1"]              = { name = "Pleasure", emote = "KIT_EMOTE_GREET_GLAD_1" },
	["provoking_1"]             = { name = "Provoking", emote = "KIT_EMOTE_TAUNT_PROVOKE_1" },
	["lets_craft"]              = { name = "Lets Craft", emote = "KIT_EMOTE_ACTION_LETS_CRAFT_1" },
	["seven"]                   = { name = "Seven", emote = "KIT_EMOTE_GREET_SEVEN_1" },
	["nausea_1"]                = { name = "Nausea", emote = "KIT_EMOTE_REACTION_HURL_1" },
	["simulating_a_laugh_1"]    = { name = "Simulating a laugh", emote = "KIT_EMOTE_REACTION_SHOT_1" },
	["shoot_1"]                 = { name = "Shoot", emote = "KIT_EMOTE_ACTION_SHOOTHIP_1" },
	["thumbs_down_1"]           = { name = "Thumbs down", emote = "KIT_EMOTE_REACTION_THUMBSDOWN_1" },
	["laugh_2"]                 = { name = "Laugh 2", emote = "KIT_EMOTE_REACTION_JOVIAL_LAUGH_1" },
	["spit_1"]                  = { name = "Spit", emote = "KIT_EMOTE_ACTION_SPIT_1" },
	["stop_here_1"]             = { name = "Stop Here", emote = "KIT_EMOTE_ACTION_STOP_HERE_1" },
	["beg_for_mercy_1"]         = { name = "Beg for Mercy", emote = "KIT_EMOTE_REACTION_BEGMERCY_1" },
	["tadaaa"]                  = { name = "Tadaaa", emote = "KIT_EMOTE_GREET_TADA_1" },
	["applause_3"]              = { name = "Applause 3", emote = "KIT_EMOTE_REACTION_APPLAUSE_1" },
	["thanks_1"]                = { name = "Thanks", emote = "KIT_EMOTE_REACTION_THANKS_1" },
	["respect_1"]               = { name = "Bow", emote = "KIT_EMOTE_GREET_RESPECTFUL_BOW_1" },
	["good_work_1"]             = { name = "Good work", emote = "KIT_EMOTE_GREET_HAT_TIP_1" },
	["lasso_chasing_1"]         = { name = "Lasso chasing", emote = "KIT_EMOTE_GREET_GET_OVER_HERE_1" },
	["send_a_kiss_1"]           = { name = "Send a Kiss", emote = "KIT_EMOTE_GREET_FLYING_KISS_1" },
	["this_one_1"]              = { name = "This one", emote = "KIT_EMOTE_REACTION_THIS_GUY_1" },
	["giving_up_1"]             = { name = "Giving up", emote = "KIT_EMOTE_REACTION_SURRENDER_1" },
	["howl_1"]                  = { name = "Howl", emote = "KIT_EMOTE_ACTION_HOWL_1" },
	["joy_5"]                   = { name = "Joy 5", emote = "KIT_EMOTE_DANCE_OLD_A_1" },
	["show_1"]                  = { name = "Show", emote = "KIT_EMOTE_ACTION_POINT_1" },
	["follow_me"]               = { name = "Follow Me", emote = "KIT_EMOTE_ACTION_FOLLOW_ME_1" },
	["cry_1"]                   = { name = "Cry", emote = "KIT_EMOTE_REACTION_SOB_1" },
	["spooky_2"]                = { name = "Spooky 2", emote = "KIT_EMOTE_ACTION_SPOOKY_1" },
	["bring_in_1"]              = { name = "Bring in", emote = "KIT_EMOTE_ACTION_BECKON_1" },
	["joy_4"]                   = { name = "Joy 4", emote = "KIT_EMOTE_DANCE_WILD_A_1" },
	["threatning_1"]            = { name = "Threatning", emote = "KIT_EMOTE_TAUNT_THROAT_SLIT_1" },
	["idea_1"]                  = { name = "Idea", emote = "KIT_EMOTE_ACTION_IDEA_1" },
	["hypnotize_1"]             = { name = "Hypnotize", emote = "KIT_EMOTE_ACTION_HYPNOSIS_POCKET_WATCH_1" },
	["greeting_1"]              = { name = "Fancy Bow", emote = "KIT_EMOTE_GREET_FANCY_BOW_1" },
	["yousmell"]                = { name = "You smell", emote = "KIT_EMOTE_TAUNT_YOUSTINK_1" },
	["rage"]                    = { name = "Rage!", emote = "KIT_EMOTE_TAUNT_WAR_CRY_1" },
	["provoking_6"]             = { name = "Provoking 6", emote = "KIT_EMOTE_TAUNT_CRUISING_BRUISING_1" },
	["fuck_off_2"]              = { name = "Fuck off 2", emote = "KIT_EMOTE_TAUNT_FINGER_SLINGER_1" },
	["joy_6"]                   = { name = "Joy 6", emote = "KIT_EMOTE_ACTION_SKYWARD_SHOOTING_1" },
	["joy_3"]                   = { name = "Joy 3", emote = "KIT_EMOTE_DANCE_WILD_B_1" },
	["give_a_coin_1"]           = { name = "give a coin", emote = "KIT_EMOTE_ACTION_BITING_GOLD_COIN_1" },
	["thumbs_up"]               = { name = "Thumbs Up", emote = "KIT_EMOTE_GREET_THUMBSUP_1" },
	["joy_1"]                   = { name = "Joy", emote = "KIT_EMOTE_TAUNT_GORILLA_CHEST_1" },
	["hush"]                    = { name = "hush", emote = "KIT_EMOTE_REACTION_HUSH_YOUR_MOUTH_1" },
	["snarl"]                   = { name = "Snarl", emote = "KIT_EMOTE_TAUNT_COUGAR_SNARL_1" },
	["malignant_revenge"]       = { name = "Malignant Revenge", emote = "KIT_EMOTE_ACTION_SCHEME_1" },
	["provoking_4"]             = { name = "Provoking 4", emote = "KIT_EMOTE_TAUNT_FIDDLEHEAD_1" },
	["agree_1"]                 = { name = "Agree", emote = "KIT_EMOTE_REACTION_NOD_HEAD_1" },
	["sniffing_1"]              = { name = "Sniffing", emote = "KIT_EMOTE_REACTION_SNIFFING_1" },
	["fish"]                    = { name = "Fish", emote = "KIT_EMOTE_ACTION_LETS_FISH_1" },
	["look_1"]                  = { name = "Look", emote = "KIT_EMOTE_ACTION_LOOK_DISTANCE_1" },
	["provoking_8"]             = { name = "Provoking 8", emote = "KIT_EMOTE_TAUNT_BEST_SHOT_1" },
	["provoking_3"]             = { name = "Provoking 3", emote = "KIT_EMOTE_TAUNT_IM_WATCHING_YOU_1" },
	["applause_2"]              = { name = "Applause 2", emote = "KIT_EMOTE_REACTION_CLAP_ALONG_1" },
	["excited_1"]               = { name = "Excitement", emote = "KIT_EMOTE_ACTION_HISSYFIT_1" },
	["look_at_the_time"]        = { name = "Look at the time!", emote = "KIT_EMOTE_ACTION_CHECK_POCKET_WATCH_1" },
	["fuck_off_1"]              = { name = "Fuck off", emote = "KIT_EMOTE_TAUNT_FLIP_OFF_1" },
	["who_me"]                  = { name = "Who? me??", emote = "KIT_EMOTE_REACTION_WHO_ME_1" },
	["provoking_2"]             = { name = "Provoking 2", emote = "KIT_EMOTE_TAUNT_INSIGNIFICANT_1" },
	["taste_2"]                 = { name = "Drink", emote = "KIT_EMOTE_ACTION_WET_YOUR_WHISTLE_1" },
	["toss_a_coin_1"]           = { name = "Toss a coin", emote = "KIT_EMOTE_ACTION_COIN_FLIP_1" },
	["provoking_5"]             = { name = "Provoking 5", emote = "KIT_EMOTE_TAUNT_CUCKOO_1" },
	["applaud_music_7"]         = { name = "Applaud to music 7", emote = "KIT_EMOTE_DANCE_FORMAL_A_1" },
	["handwriting_1"]           = { name = "Typing in notepad", emote = "KIT_EMOTE_ACTION_TAKE_NOTES_1" },
	["thumbs_up_2"]             = { name = "Good work 2", emote = "KIT_EMOTE_GREET_HAT_FLICK_1" },
	["rage_fist_pump"]          = { name = "Joy 7", emote = "KIT_EMOTE_ACTION_FIST_PUMP_1" },
	["rock_paper_scissors"]     = { name = "Rock Paper Scissors", emote = "KIT_EMOTE_ACTION_ROCK_PAPER_SCISSORS_1" },
	["cry_hangover"]            = { name = "Hangover", emote = "KIT_EMOTE_REACTION_HANGOVER_1" },
	["facepalm_1"]              = { name = "Facepalm", emote = "KIT_EMOTE_REACTION_FACEPALM_1" },
	["dance_drunk_a"]           = { name = "Applaud to music 5", emote = "KIT_EMOTE_DANCE_DRUNK_A_1" },
	["listen_1"]                = { name = "Listen", emote = "KIT_EMOTE_ACTION_LISTEN_1" },
	["showtime_tadaa"]          = { name = "Tadaaa", emote = "KIT_EMOTE_GREET_TADA_1" },
	["joy_2"]                   = { name = "Joy 2", emote = "KIT_EMOTE_REACTION_YEEHAW_1" },
	["over_there"]              = { name = "Over there", emote = "KIT_EMOTE_ACTION_LETS_GO_1" },
	["snot_1"]                  = { name = "Snot", emote = "KIT_EMOTE_ACTION_SNOT_ROCKET_1" },
	["plucking_2"]              = { name = "Plucking 2", emote = "KIT_EMOTE_DANCE_AWKWARD_A_1" },
	["provoking_6"]             = { name = "Provoking 6", emote = "KIT_EMOTE_TAUNT_CRUISING_BRUISING_1" },
	["idea_1"]                  = { name = "Idea", emote = "KIT_EMOTE_ACTION_IDEA_1" },
	["cry_1"]                   = { name = "Cry", emote = "KIT_EMOTE_REACTION_SOB_1" },
	["drinking_cowboy_1"]       = { name = "Drinking Cowboy 1", emote = "KIT_EMOTE_ACTION_DRINKING_COWBOY_1" },
	["drinking_drifter_1"]      = { name = "Drinking Drifter 1", emote = "KIT_EMOTE_ACTION_DRINKING_DRIFTER_1" },
	["drinking_secret_1"]       = { name = "Drinking Secret 1", emote = "KIT_EMOTE_ACTION_DRINKING_SECRET_1" },
	["look_yonder"]             = { name = "Look Yonder", emote = "KIT_EMOTE_ACTION_LOOK_YONDER_1" },
	["emote_action_newthreads"] = { name = "New Threads", emote = "KIT_EMOTE_ACTION_NEWTHREADS_1" },
	["spin_and_aim"]            = { name = "Spin and Aim", emote = "KIT_EMOTE_ACTION_SPIN_AND_AIM_1" },
	["smoke_cigarette"]         = { name = "Smoke Cigarette", emote = "KIT_EMOTE_ACTION_SMOKE_CIGARETTE_1" },
	["smoke_cigar"]             = { name = "Smoke Cigar", emote = "KIT_EMOTE_ACTION_SMOKE_CIGAR_1" },
	["lets_play_cards"]         = { name = "Let's Play Cards", emote = "KIT_EMOTE_ACTION_LETS_PLAY_CARDS_1" },
	["lets_craft_1"]            = { name = "Let's Craft 1", emote = "KIT_EMOTE_ACTION_LETS_CRAFT_1" },
	["slow_clap"]               = { name = "Slow Clap", emote = "KIT_EMOTE_REACTION_SLOW_CLAP_1" },
	["shuffle_1"]               = { name = "Shuffle", emote = "KIT_EMOTE_REACTION_SHUFFLE_1" },
	["dance_awkward_a"]         = { name = "Dance Awkward A", emote = "KIT_EMOTE_DANCE_AWKWARD_A_1" },
	["dance_carefree_a"]        = { name = "Dance Carefree A", emote = "KIT_EMOTE_DANCE_CAREFREE_A_1" },
	["dance_carefree_b"]        = { name = "Dance Carefree B", emote = "KIT_EMOTE_DANCE_CAREFREE_B_1" },
	["dance_confident_a"]       = { name = "Dance Confident A", emote = "KIT_EMOTE_DANCE_CONFIDENT_A_1" },
	["dance_confident_b"]       = { name = "Dance Confident B", emote = "KIT_EMOTE_DANCE_CONFIDENT_B_1" },
	["dance_drunk_a"]           = { name = "Dance Drunk A", emote = "KIT_EMOTE_DANCE_DRUNK_A_1" },
	["dance_drunk_b"]           = { name = "Dance Drunk B", emote = "KIT_EMOTE_DANCE_DRUNK_B_1" },
	["dance_formal_a"]          = { name = "Dance Formal A", emote = "KIT_EMOTE_DANCE_FORMAL_A_1" },
	["dance_graceful_a"]        = { name = "Dance Graceful A", emote = "KIT_EMOTE_DANCE_GRACEFUL_A_1" },
	["dance_old_a"]             = { name = "Dance Old A", emote = "KIT_EMOTE_DANCE_OLD_A_1" },
	["dance_wild_a"]            = { name = "Dance Wild A", emote = "KIT_EMOTE_DANCE_WILD_A_1" },
	["dance_wild_b"]            = { name = "Dance Wild B", emote = "KIT_EMOTE_DANCE_WILD_B_1" },
	["prospector_jig"]          = { name = "Prospector Jig", emote = "KIT_EMOTE_ACTION_PROSPECTOR_JIG_1" },
	["shrug"]                   = { name = "Shrug", emote = "KIT_EMOTE_REACTION_SHRUG_1" },
	["finger_salute_1"]         = { name = "Finger Salute", emote = "KIT_EMOTE_GREET_FINGER_SALUTE_1" },
	["hey_you"]                 = { name = "Hey You", emote = "KIT_EMOTE_GREET_HEY_YOU_1" },
}

Config.AnimationsToInclude = {
	"holdbars",
	"holdspear",
	"lasso",
	"broomrest",
	"poleshoulder",
	"holstergrip",
	"pee",
	"spit",
	"spit2",
	"spit3",
	"spit4",
	"spit5",
	"holdrod",
	"test",
	"carrypole",
	"holdpole",
	"raisearm",
	"blacksmith",
	"inspect",
	"riflehold",
	"swordpose",
	"swordplaying1",
	"swordplaying2",
	"smokecigarette_loop",
	"fan2",
	"relax",
	"dogbarkup",
	"bardrinking2",
	"hand_left",
	"slap1",
	"silly",
	"smokecigarette_loop_f",
	"pissoff",
	"dogbone",
	"umbrella",
	"gimmebreak",
	"stroller",
	"talk2",
	"holdtorch",
	"readnewspaper",
	"bardrinking1",
	"of_course",
	"point",
	"carrybucket",
	"aimgun3upper",
	"holdcandle",
	"aimgun3",
	"smokecigar_loop_f",
	"kneel",
	"you_hard",
	"sittinginlap",
	"parasol",
	"understand",
	"ciga",
	"lockpick",
	"hug2",
	"come_here_soft",
	"broom1",
	"me?",
	"talk3",
	"smokecigarette_f",
	"userious",
	"aimgun4",
	"pushwagon",
	"comehere",
	"dance1",
	"cough",
	"doctor",
	"rake",
	"how_much",
	"prone",
	"holdmap",
	"despair",
	"carryplank2",
	"sellnewspaper",
	"smokecigarette",
	"nervous_shoulder_stretching",
	"inspectcard",
	"drag",
	"nod",
	"crouch",
	"pointangry",
	"faceriding",
	"punch2",
	"god",
	"dogsniff",
	"smokecigar_alt2_f",
	"hat",
	"inspectpaper",
	"slap8",
	"carrybag",
	"carrysuitcase",
	"moonshine",
	"lay",
	"gunidle",
	"smokecigar2",
	"smokecigar3",
	"smokecigar4",
	"cigaridle",
	"cigaridle2",
	"cigaridle3",
	"carrybox",
	"firewood_carry",
	"broom2",
	"chairmissionary",
	"pitchfork",
	"kiss",
	"protest3",
	"supertonic",
	"isaidno",
	"carrycrate",
	"salute",
	"dance",
	"broom4",
	"nod_no_hard",
	"butwhy",
	"smokecigar",
	"me_hard",
	"slap5",
	"lay6",
	"no_way",
	"threaten",
	"shoveldirt",
	"aimgun4upper",
	"slap2",
	"dogrest",
	"aimgun2upper",
	"smokecigar_alt2",
	"dogbarkground",
	"slap6",
	"mine2",
	"dogroll",
	"goaway",
	"carrycrate4",
	"lay5",
	"dogsleep",
	"nono",
	"nod_yes_soft",
	"is_this_it",
	"carryplank",
	"fuckit",
	"carrycrate2",
	"mine",
	"letteropen2",
	"holdnewspaper",
	"aimgun1upper",
	"sniff",
	"fuckoff",
	"pet",
	"holdbaby",
	"stick",
	"*****",
	"lay4",
	"enough",
	"throwstones",
	"hey",
	"holster",
	"lay2",
	"bouquet",
	"im_telling_you",
	"spank",
	"cig",
	"handsup",
	"stop",
	"lay3",
	"riflewalk",
	"pitchfork2",
	"bring_it_on",
	"crouchenter",
	"clipboard",
	"shrug_hard",
	"smokecigarette_alt2",
	"fiddle",
	"suitcase",
	"pleased",
	"dogbeg",
	"takeoffercard",
	"slap3",
	"carrybaby",
	"broom3",
	"carrycrate3",
	"letterclose2",
	"youandme",
	"pet2",
	"hammer",
	"howshort",
	"why_left",
	"dogsit",
	"pet1",
	"cowgirl2",
	"grandpawalk",
	"sawwood",
	"why",
	"hostage",
	"groom",
	"slap7",
	"slap4",
	"dance2",
	"head_no",
	"holdmap2",
	"exactly",
	"hello",
	"damn",
	"damn_alt",
	"bring_it",
	"smokecigar_loop",
	"say_again",
	"syringe",
	"hug",
	"cry",
	"we_can_do_it",
	"i_said_no",
	"i_dont_have",
	"newspaperopen",
	"how_could_you",
	"dont_know",
	"drunkhomeless",
	"doghat",
	"displeased",
	"you_soft",
	"hand_down",
	"hand_right",
	"what_soft",
	"riflecheck",
	"what_hard",
	"dont_u_dare",
	"me",
	"handsonhip",
	"handsonhip_upper",
	"handsbehindback",
	"crossarm",
	"vomit",
	"knockeddown",
	"priestidle",
	"scared",
	"cower",
	"shake_fist",
	"hostagesit",
	"nod_yes_hard",
	"come_here_hard",
	"punch1",
	"come_on",
	"hellno",
	"foldarms",
	"protest2",
	"protest",
	"carrypick",
	"i_cant_say",
	"shrug_soft",
	"anger",
	"getspanked",
	"unbelievable",
	"forgetit",
	"imtellingya",
	"cowgirl",
	"negative",
	"eyy",
	"saluteexaggarated",
	"flip",
	"shutup",
	"how",
	"fan",
	"dogchewbone",
	"rifleidle",
	"aimgun2",
	"smokecigarette_alt2_f",
	"aimgun1",
	"smokecigar_alt1_f",
	"saluteonce",
	"bye_soft",
	"basket",
	"carrycotton2",
	"carrycotton",
	"carrybox2",
	"nod_no_soft",
	"letterclose1",
	"carrysledgehammer",
	"dogwagtail",
	"letteropen1",
	"amazing",
	"smokecigarette_alt1",
	"firewood_putdown",
	"firewood_fire",
	"bouquet2",
	"planewood",
	"talk1",
	"salutecringe",
	"bandage",
	"smokecigar_alt1",
	"paper",
	"smokecigar_f",
	"smokecigarette_alt1_f",
	"sledgehammer",
	"pee2",
	"pee3",
	"pee4",
	"pee5",
	"pee6",
	"pee7",
	"pee8",
}

Config.RailingProps = {
	"ann_05_rail01x",
	"ann_05_rail02x",
	"ann_05_rail03x",
	"ann_05_rail04x",
	"cat_rail_01",
	"hotel_ext_rail_01",
	"hotel_ext_rail_02",
	"hotel_ext_rail_03",
	"k_w_brbd_wire_fence_01",
	"k_w_brbd_wire_fence_02",
	"k_w_wire_fence_01",
	"k_w_wire_fence_02",
	"mp001_p_mp_jump_fencelong01",
	"mp001_p_mp_jump_fenceshort01",
	"mp001_p_mp_jump_fenceshort02",
	"mp001_p_railroadtiepile01x",
	"p_app_stablefence01ax",
	"p_app_stablefence01x",
	"p_app_stablefence02x",
	"p_app_stablefence03x",
	"p_app_stablefence04x",
	"p_app_stablefence05x",
	"p_app_stablefence06x",
	"rho_hotel_balustairs",
	"rho_hotel_baluster",
	"rho_hotel_baluster2",
	"p_bra_fence01x",
	"p_bra_fence02x",
	"p_bra_fence03x",
	"p_bra_fencepost01x",
	"p_cal_fence01x",
	"p_cal_fence02x",
	"p_cal_fence03x",
	"p_cal_fence04x",
	"p_cal_fencepost01x",
	"p_chickenfence01x",
	"p_chickenfence02x",
	"p_chickenfence03x",
	"p_chickenfencepost",
	"p_doorfencetall01x_l",
	"p_doorfencetall01x_r",
	"p_emrfence02ax",
	"p_emrfence02bx",
	"p_emrfence02cx",
	"p_emrfence02dx",
	"p_emrfence03ax",
	"p_emrfence03bx",
	"p_emrfence03cx",
	"p_emrfencegatel02x",
	"p_emrfencegatel03x",
	"p_emrfencegater02x",
	"p_emrfencegater03x",
	"p_emrfencepost02x",
	"p_fence01ax",
	"p_fence01bx",
	"p_fence01bxnew",
	"p_fence01cx",
	"p_fence02_post",
	"p_fence02_postx",
	"p_fence02_snglpost",
	"p_fence02_snglpostx",
	"p_fence02ax",
	"p_fence02ax_gate",
	"p_fence02bx",
	"p_fence02cx",
	"p_fence02dx",
	"p_fence02x",
	"p_fence03_post_snow",
	"p_fence03_post_snowx",
	"p_fence03a_sngl_snow",
	"p_fence03b_sngl_snow",
	"p_fence03b_sngl_snowx",
	"p_fence03c_sngl_snow",
	"p_fence03cx",
	"p_fence03d_sngl_snow",
	"p_fence04ax",
	"p_fence04bx",
	"p_fence04cx",
	"p_fence06ax",
	"p_fence06bx",
	"p_fence06cx",
	"p_fence06dx",
	"p_fence06ex",
	"p_fence06fx",
	"p_fence06gx",
	"p_fence06hx",
	"p_fence09ax",
	"p_fence10cx",
	"p_fence10cx_fall",
	"p_fence11bx",
	"p_fence11x",
	"p_fence12x",
	"p_fence13x",
	"p_fence14",
	"p_fence14x",
	"p_fence_cattle01x",
	"p_fence_cattle01x_post01",
	"p_fence_cattle02x",
	"p_fence_cattle03x",
	"p_fence_cattle04x",
	"p_fence_cattle05x",
	"p_fence_lorge01x",
	"p_fence_lorge02x",
	"p_fence_lorgepost01x",
	"p_fence_picket_01_rhoa",
	"p_fence_picket_02_rhoa",
	"p_fence_picket_w_01",
	"p_fence_picket_w_02",
	"p_fence_picket_w_03",
	"p_fence_picket_w_post",
	"p_fence_plank01",
	"p_fence_plank02",
	"p_fence_plank03",
	"p_fence_plank04",
	"p_fence_plank_post01",
	"p_fence_slm_01",
	"p_fence_slm_02",
	"p_fence_slm_03",
	"p_fence_slm_04",
	"p_fence_slm_05",
	"p_fence_wall01x",
	"p_fence_wall01x_lt_gate",
	"p_fence_wall01x_rt_gate",
	"p_fence_wall02x",
	"p_fence_wall03x",
	"p_fence_wall04x",
	"p_fence_wht_01x",
	"p_fence_wht_post",
	"p_fence_wht_postx",
	"p_fencebeamstandard_qpa_01ax",
	"p_fencebreakpost01x",
	"p_fenceghosttown_qpb_01ax",
	"p_fenceghosttown_qpb_01bx",
	"p_fencepoststandard01x",
	"p_fencepoststandard_qpa_02bx",
	"p_fencepoststandard_qpa_03x",
	"p_fencepoststick_qpc_01x",
	"p_fenceslant01x",
	"p_fenceslant02x",
	"p_fencetall_04ax",
	"p_fencetall_04ax_gate",
	"p_fencetall_04bx",
	"p_fencetall_04cx",
	"p_fencetall_04dx",
	"p_fencetall_04ex",
	"p_fencetall_04fx",
	"p_fencetall_04gx",
	"p_fencetall_04hx",
	"p_fencetall_04icv",
	"p_fencetall_04ix",
	"p_fencetall_04jx",
	"p_fencetall_05a",
	"p_fencetall_05b",
	"p_fencetall_05c",
	"p_fencetall_05d",
	"p_fencetall_05e",
	"p_gen_fence_xpost01a",
	"p_gen_fence_xpost01b",
	"p_gen_fence_xpost01c",
	"p_gen_hi_fence01",
	"p_pronghorn_fence_01a",
	"p_pronghorn_fence_01b",
	"p_pronghorn_fence_01c",
	"p_pronghorn_fence_01d",
	"p_propemfence01x",
	"p_propemfence02x",
	"p_railing_des",
	"p_rid_fence01x",
	"p_rid_fence02x",
	"p_rid_fence03x",
	"p_rid_fence04x",
	"p_rid_fence_post01x",
	"p_snow_stablefence01x",
	"p_snow_stablefence02x",
	"p_snow_stablefence03x",
	"p_snow_stablefence04x",
	"p_snow_stablefence05x_post",
	"p_val_fencez_bentl",
	"p_val_fencez_bentr",
	"p_val_fencez_blcd01x",
	"p_val_fencez_blcd02x",
	"p_val_fencez_brkna",
	"p_val_fencez_brknb",
	"p_val_fencez_falla",
	"p_val_fencez_fallb",
	"p_val_fencez_flata",
	"p_val_fencez_flatb",
	"p_val_fencez_loosea",
	"p_val_fencez_looseb",
	"p_val_fencez_loosec",
	"p_val_fencez_posta",
	"prop_test_fence_cam_01",
	"prop_test_fence_cam_2",
	"prop_test_fence_cam_3",
	"s_deerfence01x",
	"s_proghornfence01x",
	"s_proghornfence02x",
	"val_fencepen01_ax",
	"val_fencepen01_bx",
	"val_fencepen01_cx",
	"val_fencepen01_dx",
	"val_fencepen01_ex",
	"val_fencepen01_fx",
	"val_p_fenceaa",
	"val_p_fenceab",
	"val_p_fenceac",
	"val_p_fenceagate",
	"val_p_fenceapost",
	"rho_sal_trellis_a1",
	"rho_sal_trellis_a2",
	"rho_sal_trellis_btm_root",
	"rho_sal_trellisdeco_top",
}

-- ["script_re@foot_robbery@leymone"] = {
-- 	"private_conv_l_thug_b",
-- 	"private_conv_r_thug_b",
-- 	"wall_breakout_back_thug_a",
-- 	"wall_breakout_back_thug_a_thug_a",
-- 	"wall_breakout_back_vic",
-- 	"wall_breakout_left_thug_a",
-- 	"wall_breakout_left_thug_a_thug_a",
-- 	"wall_breakout_left_vic",
-- 	"wall_breakout_right_thug_a",
-- 	"action_c_thug_a_thug_a",
-- 	"wall_breakout_right_thug_a_thug_a",
-- 	"wall_breakout_right_vic",
-- 	"wall_brkout_back_thug_a",
-- 	"wall_brkout_left_thug_a",
-- 	"ground_breakout_back_thug_a",
-- 	"wall_brkout_right_thug_a",
-- 	"ground_breakout_back_thug_a_thug_a",
-- 	"ground_breakout_back_vic",
-- 	"wall_brkout_right_vic",
-- 	"ground_breakout_left_thug_a",
-- 	"ground_breakout_left_thug_a_thug_a",
-- 	"ground_breakout_left_vic",
-- 	"ground_breakout_right_thug_a",
-- 	"ground_breakout_right_thug_a_thug_a",
-- 	"ground_breakout_right_vic",
-- 	"ground_brkout_back_thug_a",
-- 	"ground_brkout_back_vic",
-- 	"ground_brkout_left_thug_a",
-- 	"ground_brkout_left_vic",
-- 	"ground_brkout_right_thug_a",
-- 	"ground_brkout_right_vic",
-- 	"wall_brkout_back_vic",
-- 	"action_a_p1_vic",
-- 	"action_a_p1_thug_b",
-- 	"action_c_vic",
-- 	"ground_loop_thug_a",
-- 	"wall_brkout_left_vic",
-- 	"quick_throw_thug_a",
-- 	"ground_loop_thug_b",
-- 	"action_a_p1_thug_a",
-- 	"action_c_thug_b",
-- 	"quick_throw_thug_b",
-- 	"ground_loop_vic",
-- 	"quick_throw_vic",
-- 	"alright_thug_a",
-- 	"action_a2_vic",
-- 	"action_c_thug_a",
-- 	"loop_thug_a",
-- 	"wall_brkout_thug_a",
-- 	"wait_loop_thug_a",
-- 	"action_a2_thug_b",
-- 	"wall_brkout_thug_b",
-- 	"wait_loop_thug_b",
-- 	"action_b_vic",
-- 	"loop_thug_b",
-- 	"wait_loop_vic",
-- 	"wall_brkout_vic",
-- 	"action_b_thug_b",
-- 	"action_a2_thug_a",
-- 	"loop_vic",
-- 	"action_b_thug_a",
-- 	"action_a_vic",
-- 	"dont_buttin_r_thug_b",
-- 	"action_a_thug_b",
-- 	"action_a_thug_a",
-- 	"action_a_p3_vic",
-- 	"ground_brkout_thug_a",
-- 	"action_a_p3_thug_b",
-- 	"action_a_p3_thug_a",
-- 	"ground_brkout_thug_b",
-- 	"action_a_p2_vic",
-- 	"action_a_p2_thug_b",
-- 	"dont_buttin_l_thug_b",
-- 	"ground_brkout_vic",
-- 	"action_a_p2_thug_a",
-- },
-- ["script_re@town_widow@give_money"] = {
-- 	"brkout_back_l",
-- 	"brkout_back_r",
-- 	"brkout_l",
-- 	"brkout_n",
-- 	"brkout_r",
-- 	"exit",
-- 	"lookup_back_l",
-- 	"lookup_back_r",
-- 	"lookup_l",
-- 	"lookup_n",
-- 	"lookup_r",
-- 	"l_hit_money",
-- 	"l_hit_money_money",
-- 	"l_hit_money_player",
-- 	"l_take_money",
-- 	"l_take_money_money",
-- 	"l_take_money_player",
-- 	"mourning_idle",
-- 	"mourn_idle",
-- 	"mourn_idle_money",
-- 	"n_hit_money",
-- 	"n_hit_money_money",
-- 	"n_hit_money_player",
-- 	"n_take_money",
-- 	"n_take_money_money",
-- 	"n_take_money_player",
-- 	"r_hit_money",
-- 	"r_hit_money_money",
-- 	"r_hit_money_player",
-- 	"r_take_money",
-- 	"r_take_money_money",
-- 	"r_take_money_player",
--    },
