SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;



-- Create tables with utf8mb4 charset
CREATE TABLE IF NOT EXISTS `murphy_barber` (
  `charid` int(11) NOT NULL,
  `hairstyle` LONGTEXT NOT NULL DEFAULT '',
  `overlays` LONGTEXT NOT NULL DEFAULT '',
  `permanentoverlay` LONGTEXT NOT NULL DEFAULT '',
  `outfit_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `murphy_barber_preset` (
  `charid` int(11) NOT NULL,
  `outfit_id` int(11) NOT NULL,
  `price` float(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `hairstyle` LONGTEXT NOT NULL DEFAULT '',
  `overlays` LONGTEXT NOT NULL DEFAULT '',
  `gender` LONGTEXT NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Change charset for existing tables if they exist
ALTER TABLE `murphy_barber` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `murphy_barber_preset` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;