-- * ==================================================
-- * GENERAL UI & COMMON TERMS
-- * ==================================================
Lang.saveButton = "Save"
Lang.notApplicable = "N/A"
Lang.status = "Status"
Lang.facilities = "Facilities"
Lang.stable = "Stable"
Lang.wagon = "Wagon"
Lang.dressing = "Dressing"
Lang.storage = "Storage"
Lang.noFacilities = "None"
Lang.contractType = "Contract Type"
Lang.contractTypeSale = "Sale"
Lang.contractTypeRent = "Rent"
Lang.rentPeriodType = "Rent Period"
Lang.rentPeriodDaily = "Daily"
Lang.rentPeriodWeekly = "Weekly"
Lang.interiorType = "Interior Type"
Lang.price = "Price"
Lang.rent = "Rent"
Lang.availableLabel = "Available"
Lang.unavailableLabel = "Unavailable"
Lang.nameLabel = "Name"
Lang.categoryLabel = "Category"
Lang.roomsAmountLabel = "Rooms amount"
Lang.interiorLabel = "Interior"
Lang.priceLabel = "Price"
Lang.stableLabel = "Stable"
Lang.storageLabel = "Storage"
Lang.maxWeightLabel = "Max Weight"
Lang.maxSlotsLabel = "Max Slots"

Lang.setZone = "Set zone"
Lang.zoneSetLabel = "Zone set"
Lang.zoneNotSetLabel = "Zone not set"
Lang.zoneNotSetError = "You must set a zone"
Lang.shouldBeOutsideZoneError = "You must be outside the zone area"
Lang.wagonLabel = "Wagon"
Lang.dressingLabel = "Dressing"
Lang.daysSuffix = "day(s)"
Lang.weeksSuffix = "week(s)"
Lang.daySuffix = "day"
Lang.daysSuffixPlural = "days"
Lang.hourSuffix = "hour"
Lang.hoursSuffixPlural = "hours"
Lang.status = "Status"
Lang.furnituresPlaced = "Furnitures placed : %d / %d"
Lang.maxFurnituresAllowed = "Maximum furnitures allowed "
Lang.keyItemDescription = "%s's key" -- Example: "Cozy cottage's key, %s will be replaced by the house name"
Lang.yes = "Yes"
Lang.no = "No"

-- * ==================================================
-- * MENU TITLES & SUBTITLES
-- * ==================================================
Lang.editHouseTitle = "Edit House"
Lang.newHouseTitle = "New house"
Lang.editHouseSubtitle = "Edit the house"
Lang.newHouseSubtitle = "Create a new house"
Lang.manageYourHouseSubtitle = "Manage your house"
Lang.manageMyHouseTitle = "Manage my house"
Lang.enterBuildModeTitle = "Enter build mode"
Lang.leaveHouseTitle = "Leave house"
Lang.furnituresCategoriesSubtitle = "Furnitures categories"
Lang.manageHouseSubtitle = "Manage House"
Lang.manageAccessTitle = "Manage Access"
Lang.payRentTitle = "Pay Rent"
Lang.transferHouseTitle = "Transfer House"
Lang.manageAccessSubtitle = "Manage access"
Lang.whoHasAccessTitle = "Who has access"
Lang.addPlayerTitle = "Add player"
Lang.housesLotTitle = "Houses lot"
Lang.houseManagerTitle = "House Manager"
Lang.manageRealEstatesSubtitle = "Manage your real estates"
Lang.createNewHouseTitle = "Create a new house"
Lang.manageHousesTitle = "Manage houses"
Lang.manageExistingHousesSubtitle = "Manage existing houses"
Lang.openHouseMenuInterior = "Open House Menu"
Lang.houseType = "House Type"
Lang.houseTypeSubtitle = "Choose house type"
Lang.shellTypeDescription = "Choose among various shell models to define the house's interior."
Lang.mloTypeDescription = "Define the area of the house using an MLO interior id."
Lang.zoneTypeDescription = "Define the area of the house using a zone."
Lang.buildModeDescription = "Add or edit furnitures and setup storage and dressing location"
Lang.buildModeNotInside = "Build mode is only accessible while inside your house"


-- * ==================================================
-- * PROMPTS & LABELS (UI Interactions)
-- * ==================================================
Lang.enterVisitMode = "Enter Visit Mode"
Lang.leaveVisitMode = "Leave Visit Mode"
Lang.hideMenu = "Hide menu"
Lang.showMenu = "Show menu"
Lang.setHousePriceMoney = "Set Money Price"
Lang.setHousePriceGold = "Set Gold Price"
Lang.setHouseName = "Set House Name"
Lang.placeMarker = "Place marker here"
Lang.placeShell = "Place house shell"
Lang.upsertHouse = "Save house"
Lang.setStorageMaxWeight = "Set Storage Max Weight"
Lang.setStorageMaxSlot = "Set Storage Max Slots"
Lang.placeFrontDoorLabel = "Place Front Door"
Lang.placeShellLabel = "Place Shell"
Lang.contractTypeLabel = "Contract Type"
Lang.oneTimeSaleLabel = "One time sale"
Lang.rentLabel = "Rent"
Lang.rentPeriodTypeLabel = "Rent Period"
Lang.dailyRentLabel = "Daily"
Lang.weeklyRentLabel = "Weekly"
Lang.placeStableLabel = "Place Stable"
Lang.placeWagonLabel = "Place Wagon"
Lang.updateHouseLabel = "Update House"
Lang.createHouseLabel = "Create House"
Lang.accessibilityEveryone = "Everyone"
Lang.accessibilityAnyoneWithAKey = "Anyone with a key"
Lang.accessibilityList = "List"
Lang.accessibilityOnlyMe = "Only me"
Lang.housesNearbyTitle = "Houses (%s)"
Lang.numberOfUnits = "%s Unit(s)"
Lang.houseNumber = "House #%s"
Lang.noHousesAvailable = "No houses available"
Lang.placeStableSpawnLabel = "Place Stable Spawn"
Lang.placeWagonSpawnLabel = "Place Wagon Spawn"
Lang.pressToWelcome = "Press ~%s~ to welcome it"
Lang.addFurnitures = "Add Furnitures"
Lang.editFurnitures = "Edit Furnitures"
Lang.setDressingLocation = "Set Dressing Location"
Lang.setStorageLocation = "Set Storage Location"
Lang.leaveBuildMode = "Leave Build Mode"
Lang.moveFurniture = "Move Furniture"
Lang.duplicateFurniture = "Duplicate Furniture"
Lang.deleteFurniture = "Delete Furniture"
Lang.leaveEditFurnitures = "Leave Edit Mode"
Lang.leaveHouse = "Leave House"
Lang.openStorage = "Open Storage"
Lang.openDressing = "Open Dressing"
Lang.buyAndPlaceFurnitureMoney = "Buy & Place Furniture (Money)"
Lang.buyAndPlaceFurnitureGold = "Buy & Place Furniture (Gold)"
Lang.addPlayer = "Add Player"
Lang.removePlayer = "Remove Player"
Lang.housePromptGroupLabel = "Nearby Houses"
Lang.openHouseMenuPrompt = "Open House Menu"
Lang.buyHouseMoney = "Buy House with money"
Lang.buyHouseGold = "Buy House with gold"
Lang.knockOnHouse = "Knock on House"
Lang.enterHouse = "Enter House"
Lang.editHouse = "Edit House"
Lang.manageHouse = "Manage House"
Lang.visitHouse = "Visit House"
Lang.rentHouseMoney = "Rent House with money"
Lang.rentHouseGold = "Rent House with gold"
Lang.editHousePrompt = "Edit House"
Lang.deleteHousePrompt = "Delete House"
Lang.payRentMoney = "Pay Rent (Money)"
Lang.payRentGold = "Pay Rent (Gold)"
Lang.manageKeySubTitle = "Manage keys"
Lang.buyNewKeyTitle = "Buy a new key"
Lang.buyNewKeyTitleWithGold = "Buy a new key with gold"
Lang.changeKeylockTitle = "Change lock"
Lang.changeKeylockTitleWithGold = "Change lock with gold"
Lang.search = "Search..."
Lang.accessStablePrompt = "Access Stable"
Lang.accessWagonPrompt = "Access Wagon"
Lang.managePlayerPermission = "Manage player permissions"
Lang.canOpenStorage = "Can open storage"
Lang.canOpenWardrobe = "Can open wardrobe"
Lang.canAddFurnitures = "Can add furnitures"
Lang.canEditFurnitures = "Can edit furnitures"
Lang.removeDoor = "Remove this door"

Lang.door = "Door"
Lang.doorsCount = "%s door(s) added"
Lang.addDoor = "Add this door"
Lang.addDoors = "Add Doors"
Lang.setMloInterior = "Set Interior"
Lang.openDoor = "Open the door"
Lang.closeDoor = "Close the door"


-- * ==================================================
-- * INPUT PROMPTS (User text input)
-- * ==================================================
Lang.inputHouseName = "House name :"
Lang.inputMoneyPrice = "Money price : "
Lang.inputGoldPrice = "Gold price : "
Lang.inputStorageMaxWeight = "Storage maximum weight (kg):"
Lang.inputStorageMaxSlots = "Storage maximum slots:"
Lang.playerSource = "Player Source ID"
Lang.playerName = "Player Name"
Lang.searchFurnitures = "Search furniture by prop name"

-- * ==================================================
-- * NOTIFICATIONS & MESSAGES
-- * ==================================================
-- ° Success Messages
Lang.houseUpdated = "House updated!"
Lang.houseCreated = "House created!"
Lang.positionSet = "Position Set!"
Lang.playerRemovedSuccessfully = "Player removed successfully."
Lang.houseBought = "House bought successfully!"
Lang.houseBoughtWithKey = "House bought, you received x1 house key !"
Lang.furnitureBought = "Furniture bought and placed!"
Lang.houseTransferSuccess = "House transferred successfully."
Lang.accessibilitySaved = "Accessibility settings saved."
Lang.houseDeleted = "House deleted successfully."
Lang.rentPaidSuccessfully = "Rent paid successfully!"
Lang.mloInteriorSet = "House interior set successfully!"

-- ° Error Messages
Lang.cantPlaceMarkerWhileVisiting = "You cannot place a marker while in Visit Mode"
Lang.cantPlaceShellWhileVisiting = "You cannot place the shell while in Visit Mode"
Lang.nameFieldCreateHouseError = "The house name is required"
Lang.frontdoorLocationFieldCreateHouseError = "The front door location is required"
Lang.shellLocationFieldCreateHouseError = "The interior's shell should be placed"
Lang.stableLocationFieldCreateHouseError = "The stable location is required when stable is enabled"
Lang.stableSpawnLocationFieldCreateHouseError = "Stable spawn location is required when stable is enabled"
Lang.wagonLocationFieldCreateHouseError = "The wagon location is required when wagon is enabled"
Lang.wagonSpawnLocationFieldCreateHouseError = "Wagon spawn location is required when wagon is enabled"
Lang.priceNumberError = "Price should be a number"
Lang.valueNumberError = "Value should be a number"
Lang.weightNumberError = "Weight should be a number"
Lang.slotsNumberError = "Slots should be a number"
Lang.selectValidInteriorError = "Please select a valid interior first."
Lang.interiorTypeRequiredError = "An interior type must be selected."
Lang.negativePriceError = "Prices cannot be negative."
Lang.negativeStorageValuesError = "Storage weight and slots cannot be negative."
Lang.errorRemovingPlayer = "Error removing player."
Lang.errorAddingPlayer = "Error adding player."
Lang.noPermissionBuyHouse = "You don't have permission to buy this house."
Lang.houseAlreadyOwned = "This house is already owned."
Lang.noPermissionEnterBuildMode = "You don't have permission to enter build mode."
Lang.periodExceedMaxAllowedDays = "Period exceeds maximum allowed days."
Lang.periodExceedMaxAllowedWeeks = "Period exceeds maximum allowed weeks."
Lang.notEnoughMoney = "Not enough money."
Lang.notEnoughGold = "Not enough gold."
Lang.errorBuyingHouse = "Error buying house."
Lang.noPermissionEnterHouse = "You don't have permission to enter this house."
Lang.noPermissionBuyFurniture = "You don't have permission to buy furniture."
Lang.noPermissionPlaceFurniture = "You don't have permission to place furniture."
Lang.noPermissionEditFurnitures = "You don't have permission to edit furnitures."
Lang.notHouseOwner = "You are not the owner of this house."
Lang.maxFurnituresAmountReached = "Maximum amount of furnitures reached for this house type."
Lang.noPermissionSetDressingLocation = "You don't have permission to set the dressing location."
Lang.dressingNotEnable = "Dressing is not enabled for this house."
Lang.noPermissionSetStorageLocation = "You don't have permission to set the storage location."
Lang.storageNotEnable = "Storage is not enabled for this house."
Lang.noPermissionTransferHouse = "You don't have permission to transfer this house."
Lang.houseTransferFailed = "Failed to transfer house."
Lang.noPermissionOpenHouseStorage = "You don't have permission to open the house storage."
Lang.noPermissionOpenHouseWardrobe = "You don't have permission to open the house wardrobe."
Lang.noPermissionAddPlayerToHouse = "You don't have permission to add a player to this house."
Lang.houseNotFound = "House not found."
Lang.noPermissionRemovePlayerFromHouse = "You don't have permission to remove this player from the house."
Lang.invalidInput = "Invalid input provided."
Lang.noPermissionUpsertHouse = "You don't have permission to create or update houses."
Lang.noPermissionDeleteHouse = "You don't have permission to delete houses."
Lang.invalidHouseData = "Invalid house data provided."
Lang.noPermissionMoveFurniture = "You don't have permission to move furniture."
Lang.noPermissionDeleteFurniture = "You don't have permission to delete furniture."
Lang.noPermissionUpdateAccessibility = "You don't have permission to update house accessibility."
Lang.errorSavingAccessibility = "Error saving accessibility settings."
Lang.managePlayerPermissions = "Permissions"
Lang.managePlayerPermissionsSubtitle = "Set specific permissions for this player"

Lang.playerPermissionsSaved = "Player permissions saved successfully"
Lang.errorSavingPlayerPermissions = "Error saving player permissions"
Lang.houseNotForRent = "This house is not for rent."
Lang.invalidRentPeriodCount = "Invalid number of rent periods selected."
Lang.errorPayingRent = "An error occurred while paying rent."
Lang.cannotExtendRentYet = "Can't extend rent yet"
Lang.notAllowedToPayInGold = "Not allowed to pay with gold"
Lang.dontHaveKey = "You don't have the key to enter this house"
Lang.keyModeNotEnabled = "Key mode is not enabled for this server"
Lang.lockChangedSuccessfully = "Lock changed successfully! You should buy a new key."
Lang.errorChangingLock = "Error changing the house lock."
Lang.newKeyBoughtSuccessfully = "New key purchased successfully!"
Lang.errorBuyingNewKey = "Error purchasing new key."
Lang.notAllowed = "Not allowed"
Lang.notInInteriorError = "You must be inside a house to do this."
Lang.noDoorNearbyError = "No door nearby."
Lang.doorNotRegisteredError = "This door is not registered in the system."
Lang.doorAlreadyAddedError = "This door is already added to the house."
Lang.mloInteriorNotSetError = "House interior not set for this house."
Lang.mloDoorsRequiredError = "At least one door must be added."
Lang.shouldBeOutsideError = "You should leave the house to do this."
Lang.cannotBeUsedOnThisHouse = "Cannot be used on this house"
Lang.furnitureNotAllowedHere = "Furniture not allowed here"

-- ° Informational Messages
Lang.knockingOnHouse = "Someone is knocking..."
Lang.goToDoor = "Go to the door"
Lang.rentDueSoon = "Rent due within the next %s"
Lang.rentOverdueTolerance = "%s left to pay rent before the house is put back on the market"
Lang.rentPaidDuration = "Paid for %s"
Lang.availableForRent = "Available for rent"
Lang.rentExceededTolerancePeriod = "Rent expired, eviction processed"
Lang.doorAdded = "Door added to the house"
Lang.doorStateOpened = "Door is now open"
Lang.doorStateClosed = "Door is now closed"

-- * ==================================================
-- * INTERIORS CATEGORIES
-- * ==================================================

Lang.int_cat_shack = "Shacks"
Lang.int_cat_rock_shack = "Rock Shacks"
Lang.int_cat_house = "Houses"
Lang.int_cat_flat = "Flats"
Lang.int_cat_manor = "Manors"
Lang.int_cat_worker = "Workers"

-- * ==================================================
-- * FURNITURES CATEGORIES
-- * ==================================================

Lang.fur_cat_beds = "Beds"
Lang.fur_cat_carpets = "Carpets"
Lang.fur_cat_cabinets = "Cabinets"
Lang.fur_cat_chairs = "Chairs"
Lang.fur_cat_tables = "Tables"
Lang.fur_cat_desks = "Desks"
Lang.fur_cat_fireplaces = "Fireplaces"
Lang.fur_cat_lamps = "Lamps"
Lang.fur_cat_plants = "Plants"
Lang.fur_cat_sofas = "Sofas"
Lang.fur_cat_wall_decorations = "Wall Decorations"
Lang.fur_cat_decorations = "Decorations"
Lang.fur_cat_bathroom = "Bathroom"
Lang.fur_cat_kitchen = "Kitchen"
Lang.fur_cat_food = "Food"
Lang.fur_cat_curtains = "Curtains"
