CREATE TABLE IF NOT EXISTS `sirevlc_breeding_creation_cooldown` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IDENTIFIER` varchar(70) DEFAULT NULL,
  `CHARID` varchar(20) DEFAULT NULL,
  `COOLDOWN_UNTIL` int(11) NOT NULL DEFAULT 0,
  `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`ID`),
  UNIQUE KEY `uniq_player` (`IDENTIFIER`,`CHARID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;