local Config <const> = {}

-- ============================================================================
-- ⚠  MOST OF THIS CONFIG IS EDITABLE LIVE IN-GAME — DO NOT EDIT THIS FILE
-- ----------------------------------------------------------------------------
-- The following sections are persisted in the `lo_settings` SQL table and
-- edited via the admin panel (Configuration serveur tab):
--   Paycheck, Logs, DefaultGrades, Features, Performance,
--   PermissionGroup, ButtonPermissions, EntityTypes, InteractionTypes,
--   Actions
--
-- Any change you make in-game overrides the values below on boot.
-- Edit this file ONLY to set the initial defaults before the first boot.
-- ============================================================================

-- ============================================================================
-- ICON NOTE
-- ----------------------------------------------------------------------------
-- All `icon = 'fa-solid fa-...'` fields below are FontAwesome classes used by
-- the ox_lib menu provider ONLY. The VORP menu does not render icons — if you
-- run the script without ox_lib, icons are ignored silently.
-- ============================================================================

-- ============================================================================
-- LANGUAGE NOTE
-- ----------------------------------------------------------------------------
-- Built-in defaults that are shown to players/admins use `labelKey` entries
-- resolved from `locales/*.json`. The plain `label` fields remain as fallback
-- values and as examples for custom entries you add yourself.
-- Add your own <lang>.json file and pick the active language via Config.Lang
-- below. The locale loader is built into the script (no ox_lib dependency).
-- Source code comments are kept in English so the script stays readable for
-- anyone maintaining or reselling it internationally.
-- ============================================================================

-- ============================================================================
-- GENERAL
-- ============================================================================
Config.Debug = false
Config.LogLevel = 'info'                             -- Console log level: 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'off'. Lower = more output. Change live: /jc_loglevel <level> (admin). When chasing a player bug, set 'debug' or 'trace', reproduce, read the log.
Config.VersionCheck = {
    enabled   = true,                                                   -- Print a notice on server start if a newer version exists on GitHub
    repo      = 'DeVerino-DVR/lo_jobscreator-version',                  -- Public repo holding version.txt + patchnote.txt (no source code). Format 'user/repo'. Leave '' to disable.
    branch    = 'main',
    updateUrl = 'https://portal.cfx.re/assets/granted-assets',          -- Where buyers re-download an updated copy (the cfx granted assets page)
}
Config.Command = 'jobcreator'                       -- Command to open the admin menu
Config.ActionMenuKey = 'F7'                          -- Key to open the personal action menu
-- Dispatch open key: NOT bound by lo_jobscreator. ox_lib (when present)
-- registers 'dispatch' (default U) and 'cursorDispatch' (default J) via
-- lo_keysMapper. Players rebind them in-game via `/keysmenu`. Buyers running
-- the dependency-free default menu can wire their own key in
-- modules/editable/client.lua → RegisterDispatchMenuKey.
Config.WitnessSonarOffset = 50                       -- Random GPS offset (m) so cops don't see the exact spot
Config.WitnessSonarDuration = 120                    -- Max seconds the sonar GPS keeps pinging
Config.WitnessSonarStopDistance = 15.0               -- Auto-stop sonar when the player gets this close (m)
Config.PromptDistance = 2.0                          -- Max display distance for the built-in interaction prompt. Lower = player must be on the point.
Config.Lang = 'en'                                   -- Default locale, must match a file in locales/<lang>.json. Players-with-permission can override at runtime via the NUI preferences (saved server-side via KVP)
Config.PermissionGroup = { 'admin' }                 -- Groups allowed to use the creator. String or table: 'admin' or { 'admin', 'moderator' }
Config.ButtonPermissions = {
    -- Leave a list empty to inherit Config.PermissionGroup.
    -- Example: jobs = { 'admin', 'job_manager' }
    dashboard       = {},
    jobs            = {},
    gangs           = {},
    publicActions   = {},
    itemCreator     = {},
    customBlips     = {},
    customPeds      = {},
    customHorses    = {},
    audit           = {},
    templates       = {},
    backup          = {},
    serverConfig    = {},
    preferences     = {},
}
Config.ImageUrl = 'nui://vorp_inventory/html/img/items/%s.png' -- Item image URL pattern (%s = item name)

-- ============================================================================
-- ENTITY PLACEMENT MODE (peds, props, blips, markers, vehicles)
-- ----------------------------------------------------------------------------
-- 'raycast' (default) — point with the mouse, raycast hit becomes the position.
--                       Rotate with scroll wheel, validate with left click.
-- 'gizmo'             — entity is spawned in front of the player and a 3D
--                       gizmo overlay lets you drag/rotate it precisely.
--                       Toggle translate/rotate with [W]/[R], finish with
--                       [BACKSPACE]. Requires jo_libs (NUI multiplexer).
--
-- Players with the "preferences" permission can override this at runtime via
-- the in-game Settings panel; the value below is just the server-wide default.
-- ============================================================================
Config.PlacementMode = 'raycast' -- 'raycast' | 'gizmo'

-- ============================================================================
-- ITEM IMAGE UPLOAD PATH (for the "Download item image" button in the panel)
-- ============================================================================
--
-- IMPORTANT FOR SERVER OWNERS:
--   On RedM, Lua's io.open cannot reliably write across resources when the
--   server folder contains [bracketed] segments (e.g. resources/[inventory]/...)
--   or sits on a Windows mount with restricted permissions. If the auto-
--   detected path doesn't work for your install, set the ABSOLUTE path to
--   your inventory's items folder here. MUST end with a trailing slash.
--
-- Examples:
--   Windows : Config.ItemImagePath = 'C:/RedM/MyServer/resources/[inventory]/vorp_inventory/html/img/items/'
--   Linux   : Config.ItemImagePath = '/home/redm/server/resources/[inventory]/vorp_inventory/html/img/items/'
--   Other inventory : Config.ItemImagePath = '/path/to/my_inventory/web/images/'
--
-- Leave it as nil to let the resource auto-detect (works on most setups).
-- Config.ItemImagePath = 'C:/RedM/LastCountry/resources/[inventory]/vorp_inventory/html/img/items/' -- machine
Config.ItemImagePath = 'D:/LastCountryV7_VORP/resources/[inventory]/vorp_inventory/html/img/items/' -- dev
-- ============================================================================
-- FRAMEWORK BRIDGE  —  VORP only.
-- ----------------------------------------------------------------------------
-- This release supports VORP (vorp_core + vorp_inventory). When vorp_core isn't
-- running the bridge degrades to "standalone" (statebag-based, minimal).
-- Want another framework? modules/editable/framework.lua is yours to rewrite —
-- everything the script touches goes through the Framework_* functions there.
-- ============================================================================
Config.Framework = {
    force = 'auto', -- 'auto' | 'vorp' | 'standalone'

    -- Optional: if you run a separate job-management resource that exposes
    -- upsert/delete exports, declare them here and panel-created jobs/gangs get
    -- pushed to it too. Leave the table out entirely to skip (VORP has no
    -- central job registry — jobs are just strings on the character).
    -- entityExports = {
    --     vorp = { resource = 'my_jobs', upsertJob = 'AddJob', upsertGang = 'AddGang',
    --              deleteJob = 'RemoveJob', deleteGang = 'RemoveGang' },
    -- },

    -- Clothing store / wardrobe events fired when a player uses a clothing_store /
    -- clothing_wardrobe interaction. Empty 'openStore'/'openWardrobe' disables it.
    -- For full control (exports, conditional logic) override CustomOpenClothingStore /
    -- CustomOpenWardrobe in modules/editable/server.lua instead.
    clothing = {
        -- Default: jo_clothingstore (Jump-On-Studios). Common alternatives:
        --   vorp_clothing : 'vorp_clothing:OpenMenu'
        --   bcc-clothes   : 'bcc-clothes:openClothingStore'
        openStore    = 'jo_clothingstore:openStore',
        openWardrobe = 'jo_clothingstore:openWardrobe',
        storeArgs    = { useOutfitMenu = true, needInstance = false },
        wardrobeArg  = false,
        preferExport = true,
        exportResource = 'jo_clothingstore',
    },

    -- Server → client toast event used by NotifyClient. Leave nil for auto
    -- (ox_lib:notify if ox_lib is installed, otherwise vorp:TipBottom).
    notify = {
        vorp = nil, -- e.g. 'vorp:TipBottom' or 'ox_lib:notify'
    },
}

-- ============================================================================
-- UI PROVIDERS
-- If AllowInGamePreferences is true, admins can change these in-game via the
-- Preferences menu and their choice is saved per-player (KVP).
-- If false, the values below are forced for everyone and the Preferences
-- button is hidden. In that case, set your desired provider here directly.
-- Menu/Input options: 'ox_lib', 'vorp' or 'jo_libs'
-- Interaction options: 'target' (ox_target) or 'prompt' (VORP prompts)
-- NOTE: For 'jo_libs', ensure `jo_libs` is installed and `@jo_libs/init.lua`
-- is uncommented in fxmanifest.lua (shared_scripts).
-- ============================================================================
Config.AllowInGamePreferences = true
-- Menu options   : 'auto' | 'ox_lib' | 'vorp' | 'jo_libs' | 'native'
-- Input options  : 'auto' | 'ox_lib' | 'vorp' | 'jo_libs' | 'native'
-- Progress options: 'auto' | 'ox_lib' | 'vorp' | 'native'
-- 'auto'   = pick the first available (ox_lib -> jo_libs -> vorp -> native)
-- 'native' = call NativeShowMenu / NativeShowInput / NativeShowProgressBar
--            defined by the server owner in modules/editable/client.lua
Config.DefaultMenuProvider = 'auto'
Config.DefaultInputProvider = 'auto'
Config.DefaultProgressProvider = 'auto'
Config.DefaultInteractionMode = 'target'

-- ============================================================================
-- FEATURES TOGGLE
-- Enable or disable sections of the admin menu and action menu
-- Set to false to completely hide the button from the menu
-- ============================================================================
Config.Features = {
    -- Admin menu (/jobcreator)
    jobs            = true,     -- Manage Jobs button
    gangs           = false,    -- Manage Gangs button (disable if VORP has no gang system)
    publicActions   = true,     -- Manage Public Interactions button
    itemCreator     = true,     -- Item Creator button
    customBlips     = true,     -- Custom Blips button
    customPeds      = true,     -- Custom Peds button
    customVehicles  = true,     -- Custom Vehicles (standalone vehicles spawned in world)
    customHorses    = true,     -- Custom Horses (standalone horses spawned in world)
    staffTools      = true,     -- Staff Tools button (animation tester, etc.)
    preferences     = true,     -- Preferences button (menu/input/target provider)

    -- Personal action menu (master toggle — individual actions live in Config.Actions)
    personalmenu          = true,
}

-- ============================================================================
-- LOGGING (built-in Discord webhook, no external dependency)
-- Leave webhook empty to only print in server console
-- ============================================================================
Config.Logs = {
    enabled = true,
    webhook = '',
    servername = 'MyServer',
    color = 3447003,
}

-- ============================================================================
-- PAYCHECK
-- Configure which exports to use for banking and company accounts
-- Set to false to disable a specific integration
-- ============================================================================
Config.Paycheck = {
    enabled = true,
    interval = 1000 * 60 * 30,
    log = true,

    -- ── HOW THE SALARY REACHES THE PLAYER ──────────────────────────────────
    -- By default the salary is added to the player IN CASH (dollars on the
    -- character) so the script works out of the box with nothing else installed.
    --
    -- Want it deposited into a BANK instead? Set `banking.enabled = true` and
    -- point `resource` / `fn` at your banking resource's "add money to account"
    -- export (signature: exports[resource]:fn(source, amount)). Example:
    --   banking = { enabled = true, resource = 'vorp_banking', fn = 'addBankMoney' }
    --
    -- ⚠ `lo_banking` below is a PRIVATE resource — it is NOT sold and NOT bundled
    --   with this script. The entry is just the value used on the original
    --   author's production server; it stays inert as long as `enabled = false`.
    --   On any other server, leave `enabled = false` (cash) or set it to your own
    --   banking resource.
    banking = {
        enabled  = true,           -- false = pay in cash | true = deposit via the export below
        resource = 'lo_banking',    -- your banking resource name (only used when enabled = true)
        fn       = 'addBankMoney',  -- export on it: exports[resource]:fn(source, amount)
    },

    -- ── COMPANY / GANG ACCOUNTS ────────────────────────────────────────────
    -- Government-type jobs (see governmentTypes) and the 'unemployed' / 'citizen'
    -- defaults are paid by the state (the money comes from nowhere). EVERY OTHER
    -- job/gang is paid out of its boss/gang account, and the payout is skipped
    -- when that account is short. If you don't run a boss-menu / gang-menu
    -- resource exposing these exports, those salaries simply won't be paid until
    -- you wire one — or add those job types to `governmentTypes`. Pointing
    -- `resource` at something you don't have just makes the call a safe no-op.
    --   GetAccount  signature: exports[resource]:getAccountFn(jobName) -> number
    --   RemoveMoney signature: exports[resource]:removeMoneyFn(jobName, amount)
    bossAccount = {
        resource = 'lo_bossmenu',
        getAccountFn = 'GetAccount',
        removeMoneyFn = 'RemoveMoney',
    },
    gangAccount = {
        resource = 'lo_gangmenu',
        getAccountFn = 'GetAccount',
        removeMoneyFn = 'RemoveMoney',
    },

    -- Job types paid by the state (salary from nowhere, not a company account).
    governmentTypes = { 'leo', 'medic', 'gouv' },
}

-- ============================================================================
-- KEYBINDS (built-in RDR2 prompt letter + RedM control hash for cancel/complete)
-- ============================================================================
-- Each entry has a `prompt` (letter shown on the built-in RDR2 UiPrompt) AND a
-- `control` (RedM control hash used by IsControlJustPressed / IsControlJustReleased).
-- Keep them aligned so the on-screen prompt and the actual key match.
Config.Keys = {
    interact      = { prompt = 'G', control = 0x760A9C6F }, -- INPUT_CONTEXT (open interaction menu)
    cancelAction  = { prompt = 'X', control = 0x4CC0E2FE }, -- INPUT_FRONTEND_DELETE (cancel current action)
    phoneHangup   = { prompt = 'H', control = 0xF1301666 }, -- INPUT_CELLPHONE_CANCEL (hang up phone call)
    deliveryDone  = { prompt = 'L', control = 0xC7B5340A }, -- INPUT_MP_TEXT_CHAT_ALL (complete delivery)
}

-- Keys for the usable-item prompt loop (drink, eat, ...). Each entry maps a
-- locale key (used for the on-screen label) to a RedM control hash. Server
-- owners are encouraged to remap them here without touching the module code.
Config.UsableKeys = {
    use     = { labelKey = 'usable_prompt_use',     control = 0x27D1C284 }, -- INPUT_INTERACT_PICKUP
    health  = { labelKey = 'usable_prompt_health',  control = 0x760A9C6F }, -- INPUT_CONTEXT
    chug    = { labelKey = 'usable_prompt_chug',    control = 0x27D1C284 }, -- same key as `use`, different label
    stash   = { labelKey = 'usable_prompt_stash',   control = 0x7DA48D2A }, -- INPUT_FRONTEND_RB
    discard = { labelKey = 'usable_prompt_discard', control = 0x3B24C470 }, -- INPUT_FRONTEND_RT
}

-- ============================================================================
-- PERFORMANCE (optimized for 600+ players)
-- ============================================================================
Config.Performance = {
    markerRenderDistance = 30.0,
    pedRenderDistance = 50.0,
    maxRenderedPeds = 25,
    propRenderDistance = 50.0,    -- Distance at which props spawn / despawn (RDR2 entity budget)
    maxRenderedProps = 30,        -- Max simultaneous props rendered around the player
    targetRefreshInterval = 1000,
    connectedPlayerRefreshInterval = 180000, -- Server-side job/gang refresh fallback
    updateDebounce = 2000,
    pedFaceOnApproach = true,    -- Peds turn to face the player when approached
    pedFaceDistance = 3.0,       -- Distance threshold to trigger ped rotation
}

-- ============================================================================
-- DEFAULT GRADES (applied when creating a new job/gang)
-- ============================================================================
Config.DefaultGrades = {
    ['0'] = { name = 'Recrue', payment = 0 },
    ['1'] = { name = 'Employe', payment = 0 },
    ['2'] = { name = 'Manager', payment = 0 },
    ['3'] = { name = 'Co-Patron', payment = 0 },
    ['4'] = { name = 'Patron', payment = 0, isboss = true },
}

-- ============================================================================
-- ENTITY TYPES (categorization for jobs)
-- ============================================================================
Config.EntityTypes = {
    { value = 'none',   label = 'Aucun',              labelKey = 'cfg_entity_none' },
    { value = 'leo',    label = 'Forces de l\'ordre', labelKey = 'cfg_entity_leo' },
    { value = 'medic',  label = 'Médecin',            labelKey = 'cfg_entity_medic' },
    { value = 'gouv',   label = 'Gouvernement',       labelKey = 'cfg_entity_gouv' },
    { value = 'job',    label = 'Métier',             labelKey = 'cfg_entity_job' },
    { value = 'gang',   label = 'Gang',               labelKey = 'cfg_entity_gang' },
    { value = 'craft',  label = 'Artisan',            labelKey = 'cfg_entity_craft' },
    { value = 'farm',   label = 'Fermier',            labelKey = 'cfg_entity_farm' },
    { value = 'hunt',   label = 'Chasseur',           labelKey = 'cfg_entity_hunt' },
    { value = 'fish',   label = 'Pêcheur',            labelKey = 'cfg_entity_fish' },
    { value = 'trade',  label = 'Commerçant',         labelKey = 'cfg_entity_trade' },
}

-- ============================================================================
-- INTERACTION TYPES
-- isPublic = can be created as a public interaction (not linked to a job/gang)
-- ============================================================================
Config.InteractionTypes = {
    stash             = { label = 'Coffre',               labelKey = 'cfg_interaction_stash',             icon = 'fa-solid fa-box',                isPublic = true },
    shop              = { label = 'Magasin',              labelKey = 'cfg_interaction_shop',              icon = 'fa-solid fa-shopping-cart',       isPublic = false },
    farm              = { label = 'Point de Récolte',     labelKey = 'cfg_interaction_farm',              icon = 'fa-solid fa-seedling',            isPublic = true },
    process           = { label = 'Point de Traitement',  labelKey = 'cfg_interaction_process',           icon = 'fa-solid fa-cogs',                isPublic = true },
    sell              = { label = 'Point de Vente',       labelKey = 'cfg_interaction_sell',              icon = 'fa-solid fa-hand-holding-dollar', isPublic = true },
    phone             = { label = 'Téléphone',            labelKey = 'cfg_interaction_phone',             icon = 'fa-solid fa-phone',               isPublic = true },
    duty              = { label = 'Point de Service',     labelKey = 'cfg_interaction_duty',              icon = 'fa-solid fa-clock',               isPublic = false },
    craft             = { label = 'Point de Fabrication', labelKey = 'cfg_interaction_craft',             icon = 'fa-solid fa-hammer',              isPublic = true },
    clothing_store    = { label = 'Magasin Vêtement',     labelKey = 'cfg_interaction_clothing_store',    icon = 'fa-solid fa-shirt',               isPublic = true },
    clothing_wardrobe = { label = 'Vestiaire',            labelKey = 'cfg_interaction_clothing_wardrobe', icon = 'fa-solid fa-shirt',               isPublic = true },
    vehicle_garage    = { label = 'Garage',               labelKey = 'cfg_interaction_vehicle_garage',    icon = 'fa-solid fa-car',                 isPublic = true },
    delivery_point    = { label = 'Point de Livraison',   labelKey = 'cfg_interaction_delivery_point',    icon = 'fa-solid fa-truck',               isPublic = true },
    bossaction        = { label = 'Action Patron',        labelKey = 'cfg_interaction_bossaction',        icon = 'fa-solid fa-crown',               isPublic = false },
    teleport          = { label = 'Téléportation',        labelKey = 'cfg_interaction_teleport',          icon = 'fa-solid fa-location-arrow',      isPublic = true },
    stable            = { label = 'Écurie',               labelKey = 'cfg_interaction_stable',            icon = 'fa-solid fa-horse',               isPublic = true },
}

-- ============================================================================
-- PERSONAL ACTIONS
-- Per-job activation: assign actions to each job in the admin panel (EntityEditor > Actions).
-- `defaultJobTypes` = job types that get this action pre-enabled at first boot
-- (migration for existing jobs) and when creating a new job of that type.
-- Use '*' to enable by default on all jobs.
-- ============================================================================
-- Actions with `hook = 'xxx'` route to OnFeature_xxx in modules/editable/client.lua.
-- Server owners wire them to their own scripts (police, medical, mechanic, etc.).
-- Anything without a hook uses the legacy `event` trigger path.
Config.Actions = {
    handcuff = {
        label = 'Menotter',
        labelKey = 'cfg_action_handcuff',
        icon = 'fa-solid fa-handcuffs',
        type = 'target_player',
        hook = 'handcuff',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'leo' },
        featureKey = 'actionHandcuff',
    },
    search = {
        label = 'Fouiller',
        labelKey = 'cfg_action_search',
        icon = 'fa-solid fa-magnifying-glass',
        type = 'target_player',
        hook = 'search',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'leo' },
        featureKey = 'actionSearch',
    },
    revive = {
        label = 'Réanimer',
        labelKey = 'cfg_action_revive',
        icon = 'fa-solid fa-heart',
        type = 'target_player',
        hook = 'revive',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'medic' },
        featureKey = 'actionRevive',
    },
    heal = {
        label = 'Soigner',
        labelKey = 'cfg_action_heal',
        icon = 'fa-solid fa-plus',
        type = 'target_player',
        hook = 'heal',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'medic' },
        featureKey = 'actionHeal',
    },
    repair = {
        label = 'Réparer',
        labelKey = 'cfg_action_repair',
        icon = 'fa-solid fa-wrench',
        type = 'target_vehicle',
        hook = 'repair',
        distance = 5.0,
        requireOnDuty = true,
        defaultJobTypes = { 'craft' },
        featureKey = 'actionRepair',
    },
    fine = {
        label = 'Amende',
        labelKey = 'cfg_action_fine',
        icon = 'fa-solid fa-receipt',
        type = 'target_player',
        hook = 'fine',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'leo' },
        featureKey = 'actionFine',
    },
    escort = {
        label = 'Escorter',
        labelKey = 'cfg_action_escort',
        icon = 'fa-solid fa-person-walking',
        type = 'target_player',
        hook = 'escort',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'leo' },
        featureKey = 'actionEscort',
    },
    putinvehicle = {
        label = 'Mettre dans le véhicule',
        labelKey = 'cfg_action_putinvehicle',
        icon = 'fa-solid fa-car',
        type = 'target_player',
        hook = 'putinvehicle',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'leo' },
    },
    pullout = {
        label = 'Sortir du véhicule',
        labelKey = 'cfg_action_pullout',
        icon = 'fa-solid fa-car',
        type = 'target_player',
        hook = 'pullout',
        distance = 3.0,
        requireOnDuty = true,
        defaultJobTypes = { 'leo' },
        featureKey = 'actionEscort',
    },
    bills = {
        label = 'Factures',
        labelKey = 'cfg_action_bills',
        icon = 'fa-solid fa-file-invoice',
        type = 'client_event',
        hook = 'bills',
        requireOnDuty = true,
        defaultJobTypes = { 'job', 'craft', 'trade' },
        featureKey = 'actionBills',
    },
    dispatch = {
        label = 'Dispatch',
        labelKey = 'cfg_action_dispatch',
        icon = 'fa-solid fa-phone',
        type = 'client_event',
        event = 'lo_jobscreator:client:openDispatchMenu',
        requireOnDuty = true,
        defaultJobTypes = { 'leo', 'medic' },
        featureKey = 'actionDispatch',
    },
    duty = {
        label = 'Service',
        labelKey = 'cfg_action_duty',
        icon = 'fa-solid fa-clock',
        type = 'self',
        event = 'lo_jobscreator:client:toggleDuty',
        requireOnDuty = false,
        defaultJobTypes = { '*' },
        featureKey = 'actionDuty',
    },
}

-- ============================================================================
-- TOWNS & DISTRICTS (for location detection in dispatch)
-- ============================================================================
-- `region` lets the dispatch broadcaster filter alerts by county/state so a
-- LEO based in New Hanover doesn't get pinged for a brawl in Tumbleweed.
-- See Config.JobRegions below to wire jobs to their coverage area.
Config.Towns = {
    { icon = 'town_annesburg',   name = 'Annesburg',   city = 7359335,     region = 'newhanover' },
    { icon = 'town_armadillo',   name = 'Armadillo',   city = -744494798,  region = 'newaustin' },
    { icon = 'town_blackwater',  name = 'Blackwater',  city = 1053078005,  region = 'westelizabeth' },
    { icon = 'town_manicato',    name = 'Manicato',    city = 1299204683,  region = 'guarma' },
    { icon = 'town_rhodes',      name = 'Rhodes',      city = 2046780049,  region = 'lemoyne' },
    { icon = 'town_saintdenis',  name = 'Saint Denis', city = -765540529,  region = 'lemoyne' },
    { icon = 'town_strawberry',  name = 'Strawberry',  city = 427683330,   region = 'westelizabeth' },
    { icon = 'town_tumbleweed',  name = 'Tumbleweed',  city = -1524959147, region = 'newaustin' },
    { icon = 'town_valentine',   name = 'Valentine',   city = 459833523,   region = 'newhanover' },
    { icon = 'town_vanhorn',     name = 'Vanhorn',     city = 2126321341,  region = 'newhanover' },
}

Config.Districts = {
    { icon = 'district_bayou_nwa',         name = 'Bayou NWA',         city = 2025841068,  region = 'lemoyne' },
    { icon = 'district_big_valley',        name = 'Big Valley',        city = 822658194,   region = 'westelizabeth' },
    { icon = 'district_bluewater_marsh',   name = 'Bluewater Marsh',   city = 1308232528,  region = 'newhanover' },
    { icon = 'district_cholla_springs',    name = 'Cholla Springs',    city = -108848014,  region = 'newaustin' },
    { icon = 'district_cumberland_forest', name = 'Cumberland Forest', city = 1835499550,  region = 'newhanover' },
    { icon = 'district_gaptooth_ridge',    name = 'Gaptooth Ridge',    city = -2066240242, region = 'newaustin' },
    { icon = 'district_great_plains',      name = 'Great Plains',      city = 476637847,   region = 'westelizabeth' },
    { icon = 'district_grizzlies',         name = 'Grizzlies',         city = -120156735,  region = 'ambarino' },
    { icon = 'district_guarma',            name = 'Guarma',            city = -512529193,  region = 'guarma' },
    { icon = 'district_heartlands',        name = 'Heartlands',        city = 131399519,   region = 'newhanover' },
    { icon = 'district_hennigans_stead',   name = "Hennigan's Stead",  city = 892930832,   region = 'newaustin' },
    { icon = 'district_rio_bravo',         name = 'Rio Bravo',         city = -2145992129, region = 'newaustin' },
    { icon = 'district_roanoake_ridge',    name = 'Roanoke Ridge',     city = 178647645,   region = 'newhanover' },
    { icon = 'district_scarlett_meadows',  name = 'Scarlett Meadows',  city = -864275692,  region = 'lemoyne' },
    { icon = 'district_tall_trees',        name = 'Tall Trees',        city = 1684533001,  region = 'westelizabeth' },
}

-- Maps a job (the framework job string) to the regions it should receive
-- dispatch alerts for. Use the `region` strings from Config.Towns/Districts
-- above. A job not listed here gets ALL alerts (legacy behavior). An empty
-- list `{}` means "no alerts at all" — useful to mute a job temporarily.
--
-- Examples (uncomment + adapt to your jobs):
--   ['police_sd']         = { 'lemoyne' },                       -- Saint Denis PD
--   ['police_valentine']  = { 'newhanover' },                     -- Valentine sheriff
--   ['police_blackwater'] = { 'westelizabeth' },                  -- Blackwater PD
--   ['police_armadillo']  = { 'newaustin' },                      -- Armadillo sheriff
--   ['police_federal']    = { 'newhanover', 'lemoyne',
--                           'westelizabeth', 'newaustin',
--                           'ambarino' },                       -- US Marshals
--   ['doctor_sd']          = { 'lemoyne', 'newhanover' },
Config.JobRegions = {
    ['stdsheriff']       = { 'lemoyne' },                                                           -- Saint Denis
    ['rhosheriff']       = { 'lemoyne' },                                                           -- Rhodes
    ['ssksheriff']       = { 'lemoyne' },                                                           -- Scarlett Meadows / Lemoyne
    ['valsheriff']       = { 'newhanover' },                                                        -- Valentine
    ['annsheriff']       = { 'newhanover' },                                                        -- Annesburg
    ['strsheriff']       = { 'westelizabeth' },                                                     -- Strawberry
    ['blwsheriff']       = { 'westelizabeth' },                                                     -- Blackwater
    ['tblsheriff']       = { 'newaustin' },                                                         -- Tumbleweed
    ['armsheriff']       = { 'newaustin' },                                                         -- Armadillo
    ['redeaglerangers']  = { 'newaustin' },                                                         -- Red Eagle Rangers
    ['marshal']          = { 'newhanover', 'lemoyne', 'westelizabeth', 'newaustin', 'ambarino' },   -- US Marshals (federal)
}

-- ============================================================================
-- MARKERS (3D world markers available for interactions)
-- ============================================================================
Config.AvailableMarkers = {
    { hash = 0x94FDAE17, name = 'Cylindre' },
    { hash = 0xEC032ADD, name = 'Anneau' },
    { hash = 0x50638AB9, name = 'Sphere' },
    { hash = 0x6EB7D3BB, name = 'Cube' },
    { hash = 0x6903B113, name = 'Halo' },
    { hash = 0xD6445746, name = 'Point Halo' },
    { hash = 0x07DCE236, name = 'Halo Rotatif' },
}

Config.PopularBlips = {
    'blip_shop_blacksmith', 'blip_shop_gunsmith', 'blip_shop_store', 'blip_shop_butcher',
    'blip_shop_horse', 'blip_shop_tailor', 'blip_shop_doctor', 'blip_shop_barber', 'blip_camp',
    'blip_campfire', 'blip_camp_tent', 'blip_campfire_full', 'blip_supplies_ammo',
    'blip_supplies_food', 'blip_supplies_health', 'blip_chest', 'blip_gang_savings', 'blip_cash_bag',
    'blip_proc_home', 'blip_proc_bank', 'blip_proc_loanshark', 'blip_ambient_new',
    'blip_ambient_chore', 'blip_ambient_hitching_post', 'blip_weapon', 'blip_weapon_handgun',
    'blip_weapon_longarm', 'blip_weapon_shotgun', 'blip_animal', 'blip_horse_owned', 'blip_stable'
}

-- ============================================================================
-- STASH BLACKLIST (items that cannot be stored in stashes)
-- ============================================================================
Config.BlackListedStorageItems = {
    'a_c_dogamericanfoxhound_01', 'a_c_dogaustraliansheperd_01', 'a_c_dogbluetickcoonhound_01',
    'a_c_dogcatahoulacur_01', 'a_c_dogchesbayretriever_01', 'a_c_dogcollie_01', 'a_c_doghobo_01',
    'a_c_doghound_01', 'a_c_doghusky_01', 'a_c_doglab_01', 'a_c_dogpoodle_01', 'a_c_dogrufus_01',
    'a_c_dogstreet_01', 'a_c_cat_01', 'a_c_sheep_01', 'a_c_squirrel_01', 'mp_a_c_fox_01',
    'mp_a_c_bighornram_01', 'a_c_skunk_01', 'a_c_raccoon_01', 'a_c_rabbit_01', 'a_c_rat_01',
    'a_c_pig_01', 'a_c_chicken_01', 'a_c_carolinaparakeet_01', 'a_c_bluejay_01', 'a_c_parrot_01',
    'a_c_woodpecker_01', 'a_c_eagle_01', 'a_c_coyote_01', 'a_c_crow_01', 'a_c_goat_01'
}

-- ============================================================================
-- SQL TABLES (auto-created on resource start, do not modify)
-- ============================================================================
Config.SQL = {
    jobs = [[
        CREATE TABLE IF NOT EXISTS `lo_jobs` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(50) NOT NULL,
            `label` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            UNIQUE KEY `name` (`name`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    gangs = [[
        CREATE TABLE IF NOT EXISTS `lo_gangs` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(50) NOT NULL,
            `label` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            UNIQUE KEY `name` (`name`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    job_interactions = [[
        CREATE TABLE IF NOT EXISTS `lo_job_interactions` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `job_name` varchar(50) NOT NULL,
            `interaction_type` varchar(50) NOT NULL,
            `coords` longtext NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            KEY `job_name` (`job_name`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    gang_interactions = [[
        CREATE TABLE IF NOT EXISTS `lo_gang_interactions` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `gang_name` varchar(50) NOT NULL,
            `interaction_type` varchar(50) NOT NULL,
            `coords` longtext NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            KEY `gang_name` (`gang_name`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    public_interactions = [[
        CREATE TABLE IF NOT EXISTS `lo_public_interactions` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `interaction_type` varchar(50) NOT NULL,
            `coords` longtext NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    daily_uses = [[
        CREATE TABLE IF NOT EXISTS `lo_daily_uses` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `use_key` varchar(255) NOT NULL,
            `use_count` int(11) NOT NULL DEFAULT 0,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            UNIQUE KEY `use_key` (`use_key`),
            KEY `created_at` (`created_at`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    total_uses = [[
        CREATE TABLE IF NOT EXISTS `lo_total_uses` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `use_key` varchar(255) NOT NULL,
            `use_count` int(11) NOT NULL DEFAULT 0,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            UNIQUE KEY `use_key` (`use_key`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    settings = [[
        CREATE TABLE IF NOT EXISTS `lo_settings` (
            `key` varchar(64) NOT NULL,
            `value` longtext NOT NULL,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`key`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    audit_log = [[
        CREATE TABLE IF NOT EXISTS `lo_audit_log` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `ts` bigint(20) NOT NULL,
            `staff_id` int(11) DEFAULT NULL,
            `staff_name` varchar(100) DEFAULT NULL,
            `action` varchar(32) NOT NULL,
            `target_type` varchar(32) NOT NULL,
            `target_name` varchar(255) DEFAULT NULL,
            `details` longtext DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `ts` (`ts`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    custom_blips = [[
        CREATE TABLE IF NOT EXISTS `lo_custom_blips` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    custom_peds = [[
        CREATE TABLE IF NOT EXISTS `lo_custom_peds` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    custom_props = [[
        CREATE TABLE IF NOT EXISTS `lo_custom_props` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    custom_markers = [[
        CREATE TABLE IF NOT EXISTS `lo_custom_markers` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    custom_vehicles = [[
        CREATE TABLE IF NOT EXISTS `lo_custom_vehicles` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    custom_horses = [[
        CREATE TABLE IF NOT EXISTS `lo_custom_horses` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(100) NOT NULL,
            `data` longtext NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
    item_usables = [[
        CREATE TABLE IF NOT EXISTS `lo_item_usables` (
            `item` varchar(64) NOT NULL,
            `data` longtext NOT NULL,
            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`item`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    ]],
}

_ENV.Config = Config
