SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;



CREATE TABLE `murphy_clothes` (
  `charid` varchar(200) NOT NULL,
  `clothes` LONGTEXT NOT NULL,
  `outfit_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `murphy_outfits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `charid` varchar(200) NOT NULL,
  `outfit_id` varchar(50) NOT NULL,
  `price` float(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `clothes` LONGTEXT NOT NULL DEFAULT '',
  `singleitems` LONGTEXT NOT NULL DEFAULT '',
  `gender` varchar(200) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `outfit_id_unique` (`outfit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `murphy_wearable` (
  `charid` varchar(200) NOT NULL,
  `outfit_id` int(11) NOT NULL,
  `skin` LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
