Lang = {}


Lang.Creator = {
    ["Ped Warning"] = "You're using a ped base, you'll need to customize their hairstyle and clothing. Makeup and lifestyle overlays won't be available.",
    ["Height"] = "Height",
    ["Body"] = "Body",
    ["Waist"] = "Waist",
    ["Legs"] = "Legs",
    ["Upper"] = "Upper",
    ["Model"] = "Model",
    ["Narrow"] = "Narrow",
    ["Wide"] = "Wide",
    ["Large"] = "Large",
    ["Small"] = "Small",
    ["Extruded"] = "Extruded",
    ["Retracted"] = "Retracted",
    ["Raised"] = "Raised",
    ["Lowered"] = "Lowered",
    ["Low"] = "Low",
    ["High"] = "High",
    ["Open"] = "Close",
    ["Close"] = "Close",
    ["Far"] = "Far",
    ["Left"] = "Left",
    ["Right"] = "Right",
    ["Down"] = "Down",
    ["Up"] = "Up",
    ["Detached"] = "Detached",
    ["Stuck"] = "Stuck",
    -- Body parts pins
    ["Head"] = "Head",
    ["Face"] = "Face",
    ["Upper Body"] = "Upper Body",
    ["Lower Body"] = "Lower Body",
    ["Hairdresser"] = "Hairdresser",
    ["Clothes"] = "Clothes",
    ["Clothes Shop"] = "Clothes Shop",
    -- Head features
    ["Head Shape"] = "Head Shape",
    ["Head Width"] = "Head Width",
    ["Face Width"] = "Face Width",
    ["Forehead Size"] = "Forehead Size",
    ["Neck"] = "Neck",
    ["Neck Width"] = "Neck Width",
    ["Neck Depth"] = "Neck Depth",
    ["Eyes"] = "Eyes",
    ["Eyes Depth/Angle"] = "Eyes Depth/Angle",
    ["Eyes Distance/Height"] = "Eyes Distance/Height",
    ["Brows"] = "Brows",
    ["Brows Height/Width"] = "Brows Height/Width",
    ["Depth"] = "Depth",
    ["Eyelid"] = "Eyelid",
    ["Eyelid Height/Width"] = "Eyelid Height/Width",
    ["Left Eyelid Opening"] = "Left Eyelid Opening",
    ["Right Eyelid Opening"] = "Right Eyelid Opening",
    ["Ears"] = "Ears",
    ["Ears Width/Angle"] = "Ears Width/Angle",
    ["Ears Height/Depth"] = "Ears Height/Depth",
    ["CheekBone"] = "CheekBone",
    ["CheekBone Height/Width"] = "CheekBone Height/Width",
    ["CheekBone Depth"] = "CheekBone Depth",
    ["Jaw"] = "Jaw",
    ["Jaw Height/Width"] = "Jaw Height/Width",
    ["Jaw Depth"] = "Jaw Depth",
    ["Chin"] = "Chin",
    ["Chin Height/Width"] = "Chin Height/Width",
    ["Chin Depth"] = "Chin Depth",
    ["Nose"] = "Nose",
    ["Nose Width/Size"] = "Nose Width/Size",
    ["Nose Height/Angle"] = "Nose Height/Angle",
    ["Nose Curvature/Distance"] = "Nose Curvature/Distance",
    ["Mouth"] = "Mouth",
    ["Tooth"] = "Teeth",
    ["Mouth Width/Depth"] = "Mouth Width/Depth",
    ["Mouth Placement"] = "Mouth Placement",
    ["Lip Upper"] = "Lip Upper",
    ["Lip Upper Height/Width"] = "Lip Upper Height/Width",
    ["Lip Upper Depth"] = "Lip Upper Depth",
    ["Lip Lower"] = "Lip Lower",
    ["Lip Lower Height/Width"] = "Lip Lower Height/Width",
    ["Lip Lower Depth"] = "Lip Lower Depth",
    ["Mouth Corner Left"] = "Mouth Corner Left",
    ["Mouth Corner Left Withd/Depth"] = "Mouth Corner Left Withd/Depth",
    ["Mouth Corner Left Height"] = "Mouth Corner Left Height",
    ["Mouth Corner Left Lips Distance"] = "Mouth Corner Left Lips Distance",
    ["Mouth Corner Right"] = "Mouth Corner Right",
    ["Mouth Corner Right Withd/Depth"] = "Mouth Corner Right Withd/Depth",
    ["Mouth Corner Right Height"] = "Mouth Corner Right Height",
    ["Mouth Corner Right Lips Distance"] = "Mouth Corner Right Lips Distance",
    ["Shoulders"] = "Shoulders",
    ["Upper Shoulders Size/Height"] = "Upper Shoulders Size/Height",
    ["Back Shoulders Thickness"] = "Back Shoulders Thickness",
    ["Back Muscles"] = "Back Muscles",
    ["Arms"] = "Arms",
    ["Arms Size"] = "Arms Size",
    ["Forearms Size"] = "ForeArms Size",
    ["Chest"] = "Chest",
    ["Chest Size/Width"] = "Chest Size/Width",
    ["Chest Height"] = "Chest Height",
    ["Anterior Trapezius"] = "Anterior Trapezius",
    ["Thights Size"] = "Tights Size",
    ["Calves Size"] = "Calves Size",
    ["Waist Width"] = "Waist Width",
    ["Hips Size"] = "Hips Size",
    


}

Lang.Categories = {
    -- Barber

    ["hair"] = "Hair",
    ["hair_bonnet"] = "Hair Bonnet",
    ["beard"] = "Beard",
    ["beards_complete"] = "Full Beards",
    ["beards_mustache"] = "Mustaches",
    ["beards_chops"] = "Sideburns",
    ["beards_chin"] = "Chin Hair",

    -- Makeup
    ["eyeliners"] = "Eyeliners",
    ["eyebrows"] = "Eyebrows",
    ["scars"] = "Scars 1",
    ["scars2"] = "Scars 2",
    ["scars3"] = "Scars 3",
    ["lipsticks"] = "Lipsticks",
    ["acne"] = "Acne",
    ["shadows"] = "Shadows",
    ["beardstabble"] = "Beard Stabble",
    ["paintedmasks"] = "Painted Masks",
    ["ageing"] = "Ageing",
    ["blush"] = "Blush",
    ["blush2"] = "Blush 2",
    ["complex"] = "Complex",
    ["disc"] = "Disc",
    ["foundation"] = "Foundation",
    ["freckles"] = "Freckles",
    ["grime"] = "Grime",
    ["hairstabble"] = "Hairstabble",
    ["moles"] = "Moles",
    ["spots"] = "Spots",

}
